### PR TITLE
fix: possible out of memory error

### PR DESCRIPTION
**Pull request by klopfdreh**
Possibly fixes: https://github.com/spring-cloud/spring-cloud-dataflow/issues/5409

As of https://dataschool.com/how-to-teach-people-sql/difference-between-where-and-on-in-sql/ some databases might join before filter which might cause out of memory exceptions because all task manifests are load.

> Different SQL languages may have different query plans based on filtering in the ON clause vs the WHERE clause, so test the performance on your database

### CODE REVIEW

**Comment by klopfdreh** [comment]
Edit: This might only optimize the performance on DB server but not cause the JVM to raise an OutOfMemoryError.

I try to figure out what's the real cause and if I find something I am going to push it into this branch. `klopfdreh:fix/outofmemory`

**Comment by corneil** [comment]
We can revisted once we have done testing on the support for Boot 3 workloads with new Spring Batch and Spring Cloud Task schemas.

**Comment by klopfdreh** [comment]
> We can revisted once we have done testing on the support for Boot 3 workloads with new Spring Batch and Spring Cloud Task schemas.

Thanks a lot! 👍

**Comment by klopfdreh** [comment]
@corneil the out of memory issue did not happened with 2.11.0 anymore. I am going to close this PR as it only changes the SQLs slightly.

**Pull request closed without merging**
