### PR TITLE
Filter job executions not integrated with Spring Cloud Task

### PR DESCRIPTION
**Pull request by aritzbastida**
(cherry picked from commit 96aa4207e63e00e411b334cd71a8037aec284916)

### CODE REVIEW

**Comment by onobc** [comment]
Hi @aritzbastida . Thanks for the PR. I am going to take a look shortly. One thing though, I can't see to find the commit that you cherry-picked from. Can you double-check and/or give me some more info on the commit? 

Thanks

**Comment by aritzbastida** [comment]
Hi! I cherry-picked from a local branch; that's why you cannot see commit 96aa420. That message was auto-generated by Git (and I did not edit it). It can be a bit misleading, sorry. 

However, the PR is self-contained. As you can see, it just contains one commit (61ef421) and one file modification, compared to branch 2.9.x.

BTW, I also opened a related issue (https://github.com/spring-cloud/spring-cloud-dataflow/issues/4803). Is that redundant with this? How should I proceed when I want to open an issue with a related PR?

**Comment by onobc** [comment]
> Hi! I cherry-picked from a local branch; that's why you cannot see commit 96aa420. That message was auto-generated by Git (and I did not edit it). It can be a bit misleading, sorry.

No problem. Thanks for the clarification.

> BTW, I also opened a related issue (#4803). Is that redundant with this? How should I proceed when I want to open an issue with a related PR?

So in Spring projects in general, if you are submitting a PR there is no need to also submit an issue. If you find an issue but only want to report it, then you can just file an issue. 

I will take a look at the code proposal later today (as soon as I free up) but one concern I have is that I see no tests updated etc.. Can you see if there is an existing test(s) that we can add/update a test to cover this case? 

Thanks

**Comment by aritzbastida** [comment]
Ok, so I won't open an issue next time. Thanks for the info! 

I just checked that this code does not break any (additional) unit test in spring-cloud-dataflow-server-core module, but did not write a new one on my own. In fact, I don't see any test for "org.springframework.cloud.dataflow.server.batch" package!

**Comment by onobc** [comment]
Hi @aritzbastida 

First off, thanks for the proposal and your efforts. 

I spoke w/ the team today in regards to this issue. Our stance is that we do not support this use case. We do understand that having the executions view throw an error is not ideal.

Currently Spring Cloud Data Flow only supports Spring Boot applications that utilize Spring Cloud Task when launching tasks.  This allows SCDF to support many types of tasks across multiple platforms including those that utilize Spring Batch.    

Again, we do appreciate your contributions and efforts.

**Comment by aritzbastida** [comment]
Ok, thanks for considering the PR! I will close the related issue (#4803) as well.

**Comment by onobc** [comment]
Thank you @aritzbastida

**Pull request closed without merging**
