### PR TITLE
Job instance filter for job executions

### PR DESCRIPTION
**Pull request by siddhantsorann**
This PR adds a feature requested in issue #4166 

The following changes were made -
- Added new API for passing the instance id to filter job executions
- Added a new DAO method to search for job executions filtered by job instance id provided.

### CODE REVIEW

**Comment by cppwfs** [comment]
@siddhantsorann Thanks again for the contribution.   
We need to add this entry to the Representation Model that is displayed when someone hits the root URL of dataflow.   This can be done by adding the following code 
```
			taskTemplated = entityLinks.linkToCollectionResource(JobExecutionThinResource.class).getHref() + "{?jobInstanceId}";
			root.add(new Link(taskTemplated).withRel("jobs/thinexecutions/jobInstanceId"));
```
to the RootController after this line:https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RootController.java#L170
Once this is complete you can your new end point when you hit `http://localhost:9393`.

**Comment by siddhantsorann** [comment]
Hey @cppwfs I have updated the PR with the requested changes.

**Comment by cppwfs** [comment]
Hmmm.   Looks like there is a build failure: https://github.com/spring-cloud/spring-cloud-dataflow/pull/4197/checks?check_run_id=1257654675

**Comment by siddhantsorann** [comment]
Hey @cppwfs Sorry, missed the failure. Have resolved it now.

**Comment by cppwfs** [comment]
Rebased, Squashed,Merged.  

@siddhantsorann, thank you for this contribution!!!!

**Pull request closed without merging**
