### PR TITLE
Corrected the usage comments

### PR DESCRIPTION
**Pull request by arnoe**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@arnoe Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=3701)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=3701) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@arnoe Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=3701)!

**Comment by ilayaperumalg** [comment]
@arnoe Thank you for the contribution! Merging.

**Comment by ilayaperumalg** [comment]
Back ported into 2.3.x as b715607ff

**Pull request merged**
