### PR TITLE
Update StreamCommands.java

### PR DESCRIPTION
**Pull request by aharonmu**
typo in help: "sort" instead of "short"

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@aharonmu Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4222)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4222) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by aharonmu** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by ilayaperumalg** [comment]
@aharonmu Thank you for the fix!

**Comment by pivotal-issuemaster** [comment]
@aharonmu This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by ilayaperumalg** [comment]
Cherry-picked and pushed into 2.6.x as ffe750f74

**Pull request merged**
