### PR TITLE
Removes deprecated spring.cloud.deployer as an app property.

### LINKED ISSUE #1756: Remove deprecated use of `spring.cloud.deployer` as an app property
https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-rest-resource/src/main/java/org/springframework/cloud/dataflow/rest/util/DeploymentPropertiesUtils.java#L146

### PR DESCRIPTION
**Pull request by cppwfs**
Looks like docs have been updated already. As far as app.*.spring.cloud.deployer references.

resolves #1756

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
LGTM

**Comment by sabbyanandan** [comment]
@ilayaperumalg: Thanks for the review! If you're good with it, please go ahead and merge it.

**Comment by ilayaperumalg** [comment]
Merging.

**Comment by ilayaperumalg** [comment]
Rebased and merged as 7c5c9224

**Pull request closed without merging**
