### PR TITLE
Fixes gh-4065: Added http client redirect strategy that removes authorization headers when detecting Amazon signed uris

### PR DESCRIPTION
**Pull request by aweigold**
Unit test spins up a Spring application as a Junit ExternalResource, as there is no way great way to test mocking the redirect with the resttemplate.  This Spring application also utilizes a signed SSL certificate as docker registry apis require TLS.

Updated jacoco maven plugin, due to build failure locally with the test application logging creating an error instead of a warning.

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@aweigold Thank you for fixing the issue and looking forward to see more feedback/contributions!

**Comment by tzolov** [comment]
@aweigold, thanks for revealing this faulty behavior! I was not aware that:
> following the redirect, as Amazon's API will return a 400 response when given more than one auth mechanism.
Is this general for all Amazon APIs or only for S3? 
Similarly is the `X-Amz-Credential` header by all AMZ apis or just S3? 

I am trying to understand the scope of this change and what side effects it might have

**Comment by tzolov** [comment]
Thanks for your contribution @aweigold ! 
I've made few minor adjustments to streamline the code and improve the class naming. 
Squashed, rebased and merged at b550ecf6abd97f54fc54563a1f710fc3299a408a

**Comment by aweigold** [comment]
> @aweigold, thanks for revealing this faulty behavior! I was not aware that:
> 
> > following the redirect, as Amazon's API will return a 400 response when given more than one auth mechanism.
> > Is this general for all Amazon APIs or only for S3?
> > Similarly is the `X-Amz-Credential` header by all AMZ apis or just S3?
> 
> I am trying to understand the scope of this change and what side effects it might have

I don't know offhand if the AMZ supports presigned urls for other apis, but doing so outside of the context of sharing an object in an S3 bucket seems very irregular and a security risk.  Doing a quick Google, it's pretty evident the common use case is S3.

IMHO, passing back presigned urls is a bad practice, as anyone who might capture that URL will have access to the resource until the credentials in the url expire.  I generally direct developers to proxy a stream from the S3 SDK, but I've seen this out in the wild (and obviously with Go Harbor) where you invoke the S3 API to generate a presigned url, to pass/redirect, back to the client.  Since the credentials in the url expire fairly quickly, it's a containable risk.

**Pull request closed without merging**
