### PR TITLE
Add properties WL expansion to task launch

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes https://github.com/spring-cloud/spring-cloud-dataflow/issues/922

### CODE REVIEW

**Comment by cppwfs** [comment]
LGTM.  Will fix the above comments on merge.

**Comment by cppwfs** [comment]
Did find one more thing before I merged.  
spring-cloud-dataflow-server-core/src/test/resources/apps/foo-task/META-INF/.vcs-dont-ignore should not be a part of this PR.  
I can remove this prior to merge.

**Comment by ericbottard** [comment]
> spring-cloud-dataflow-server-core/src/test/resources/apps/foo-task/META-INF/.vcs-dont-ignore

Yes it should. It's there so that the empty parent folder is indeed re-created by git

**Comment by ericbottard** [comment]
Feel free to add a comment in the file if it's intent is not obvious

**Comment by cppwfs** [comment]
Rebased Merged

**Pull request closed without merging**
