### PR TITLE
Update dashboard and flo screenshots

### PR DESCRIPTION
**Pull request by sabbyanandan**
This PR replaces the screenshots with the new experience. A few screenshots are under development still, but I didn't want to remove them. We can revisit it when we are done with the port by 1.3 RC timeframe.

Resolves spring-cloud/spring-cloud-dataflow#1626

### CODE REVIEW

**Comment by cppwfs** [comment]
Bulk Task Import image can be updated.  Did you want me to do that on merge?

**Comment by sabbyanandan** [comment]
Hi, @cppwfs. I just added it.

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
Squashed Merged.

**Pull request closed without merging**
