### PR TITLE
Add incremental TAB completion of configuration properties

### PR DESCRIPTION
**Pull request by ericbottard**
Instead of showing the 100s of configuration properties that are
currently visible though boot metadata, stop at each dot.

This resolves spring-cloud/spring-cloud-dataflow#187.

### CODE REVIEW

**Comment by ghillert** [comment]
Hey Eric, 

Not sure how nasty it would be, but could you provide some tests for this?

**Comment by ericbottard** [comment]
Yep, intented to add some but got carried away. Would be cool to validate the behavior before that, if you can though (ie manual tests to see how it feels)

**Comment by ghillert** [comment]
@ericbottard Cannot build after rebase with the latest from `master`. Hitting compilation errors in `spring-cloud-dataflow-completion`.

**Comment by ericbottard** [comment]
Can you paste the error ? Need https://github.com/spring-cloud/spring-cloud-stream/pull/210

**Comment by ghillert** [comment]
By the way do any of the XD-documented `http-source` properties work? Looks like things like `--port` don't show up. Otherwise, property completion works. Once you add some tests we could merge.

**Comment by ericbottard** [comment]
The option is not `port` but `server.port` (boot option)

**Comment by ghillert** [comment]
@ericbottard Shouldn't we keep certain basic properties backwards compatible?

**Comment by ericbottard** [comment]
Not for me to decide :) My understanding is that we embrace boot. cc @markfisher 
I personally don't think this is a big deal, especially if we have good discoverability of those options

**Comment by markfisher** [comment]
In general, we should maintain backwards compatibility and not rename options arbitrarily. However, the `--port` option is a special case. In fact it's handled universally for any module now via the `server.port` boot property (configurable as a deployment property rather than a "module option").

**Comment by ghillert** [comment]
Ok - cool. @ericbottard So once you have some tests in place, I can merge.

**Comment by ericbottard** [comment]
Added some tests that cover new behavior

**Comment by ghillert** [comment]
Merged with PR f584c2f

**Pull request closed without merging**
