### PR TITLE
Fix CounterController Metric value type & add tests

### LINKED ISSUE #526: CounterController should use Metric value type Long instead of Double
Currently, the CounterController uses `Metric` value as `Double` which needs to be `Long`.
and obviously, the `CounterService` persists metric value as `Long`.

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- The metric value type used in the CounterController is set to use `Long` instead of `Double`
 - Add CounterControllerTests

Resolves spring-cloud/spring-cloud-dataflow#526 
Resolves spring-cloud/spring-cloud-dataflow#460

### CODE REVIEW

**Comment by markpollack** [comment]
The RedisMetricRepository in boot actually is returning a Metric<Double>, see https://github.com/spring-projects/spring-boot/blob/master/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/repository/redis/RedisMetricRepository.java#L182

**Comment by ilayaperumalg** [comment]
It is weird that the `DefaultCounterService` uses `Double` and will have problem when using this as a `CounterService`. Since data flow explicitly uses `RedisCounterRepository`, I have updated this PR to use `Double` as the metric value type and updated the tests to use `RedisCounterRepository`.

**Comment by markpollack** [comment]
Getting a test failure on testList

```
java.lang.AssertionError: JSON path "$.page.totalElements"
Expected: is <2>
     but: was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.springframework.test.util.JsonPathExpectationsHelper.assertValue(JsonPathExpectationsHelper.java:103)
	at org.springframework.test.web.servlet.result.JsonPathResultMatchers$1.match(JsonPathResultMatchers.java:65)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:171)
	at org.springframework.cloud.dataflow.server.controller.CounterControllerTests.testList(CounterControllerTests.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
```

**Comment by markpollack** [comment]
I cleaned redis and it worked, not sure the root cause as I didn't look at my keys/contents before flushing....

**Pull request closed without merging**
