### PR TITLE
Move common security configs into spring-cloud-common-security

### LINKED ISSUE #1481: Move the common security infrastructure to a separate project
As a developer, I'd to study how to split and move the common security infrastructure to a library.

1) Remove Spring Boot's security utilities
2) Move the common code to a separate project

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Move all the extended security configuration classes into a separate project `spring-cloud-common-security` so that other projects could re-use them
 - Update `spring-cloud-common-security` as a dependency
 - Update tests

Resolves #1481

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
The repository for common security configuration is here: https://github.com/ilayaperumalg/spring-cloud-common-security

**Comment by ghillert** [comment]
@ilayaperumalg @markpollack One general concern I have is regarding naming ... `spring-cloud-common-security` would imply a general purpose project directly under `spring-cloud`. Do we think it will really be that *general purpose*? I wish there was one more layer of abstraction between *Spring Cloud* and *Spring Cloud Data Flow*.

**Comment by ilayaperumalg** [comment]
The corresponding changes in the common repo is pushed at https://github.com/ilayaperumalg/spring-cloud-common-security/commit/1015d8d25e3f0e668d2443a1f2e5f7dc77d27a69

**Comment by markpollack** [comment]
@ghillert  Looking at the repo, I don't see anything in the pom that indicates it is a 'spring-cloud' project.  Maybe we can put it under spring-projects org?  Let's get a quick take on it from Dave and Spencer, and also Rob.  ATM, the plan it to use it inside skipper for these common needs.

**Comment by sabbyanandan** [comment]
Hi, @markpollack. This library will also be used in Composed Task Runner and Metrics. The sooner we can green-light and merge it, the better it would be from testing/acceptance standpoint.

**Comment by jvalkeal** [comment]
I think repo/maven name `spring-cloud-common-security` doesn't align with java package name `org.springframework.cloud.security`. One of those needs to get changed.
Yeah, technically `org.springframework.cloud.security` belong to github.com/spring-cloud/spring-cloud-security

**Comment by ilayaperumalg** [comment]
@markpollack That's a better name! I see that we have `spring-data-commons` under `spring-projects`. Do you think we can name it as `spring-security-commons` (just to be in a similar pattern)?

**Comment by ilayaperumalg** [comment]
Created a couple of the repos:

https://github.com/ilayaperumalg/spring-security-commons
https://github.com/ilayaperumalg/spring-common-security

The project now uses `spring-boot-parent` POM.

@jvalkeal @ghillert @sabbyanandan @markpollack What do you think?

**Comment by sabbyanandan** [comment]
+1 to `spring-security-commons`.

**Comment by sabbyanandan** [comment]
@markpollack suggested `spring-common-security-config`.

**Comment by ilayaperumalg** [comment]
Closing this one to open a new PR that is based out of 1.3.

**Pull request closed without merging**
