### PR TITLE
Remove CF instructions

### PR DESCRIPTION
**Pull request by ericbottard**
see https://github.com/spring-cloud/spring-cloud-dataflow-admin-cloudfoundry/pull/2

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Shall we remove `lattice` and `yarn` (since they are already gone from this repo) instructions as part of this PR as well?

**Comment by ericbottard** [comment]
dunno if those README bits have been moved in the respective repos, but ultimately yes

**Comment by markfisher** [comment]
We can remove the others in separate PRs (once they are up to date in their new repos).

**Comment by markfisher** [comment]
rebased and merged as https://github.com/spring-cloud/spring-cloud-dataflow/commit/8860e8aba8c4d97aa1f11f6d5142ce4649f3c4a0

also left a couple comments on https://github.com/spring-cloud/spring-cloud-dataflow-admin-cloudfoundry/pull/2 since it was not updated to match the new codebase

**Pull request closed without merging**
