### PR TITLE
Remove second unescaping of Container Metadata

### LINKED ISSUE #4084: Prevent double un-escaping of container images metadata
**Description:**
SCDF uses `StringEscapeUtils#unescapeJson` to unescape the app configuration metadata retrieved from the container image.  At the same the the RestTemplate used to interact with the container registries automatically unescape the REST results.  This leads to double unescaping and invalid content for configurations with escapable characters. 

**Release versions:**
This affects the SCDF 2.6.x, 2.7.0-SNAPSHOT branches.

**Steps to reproduce:**
Register the `docker:springcloudstream/http-source-rabbit:2.1.3.RELEASE` and check the app info in SCDF.

### PR DESCRIPTION
**Pull request by tzolov**
- Delegates the unescaping to the RestTemplate interacting with the container registries.
  - Add IT test.

  Resolves #4084

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
LGTM

**Comment by ilayaperumalg** [comment]
@tzolov I think this needs to be back ported into 2.6.x as well. Would you mind creating a separate PR for 2.6.x as you have made some version updates along with this PR (which isn't scope of this though) ? Thanks!

**Comment by ilayaperumalg** [comment]
Merging.

**Comment by markpollack** [comment]
thanks for doing this for me, was just now looking into it.

**Pull request merged**
