### PR TITLE
[Do not merge yet] Add a simple out-of-process local deployer

### PR DESCRIPTION
**Pull request by ericbottard**
Discussed this a bit with Ilaya.
This turned out to be pretty easy to implement.

Say goodbye to CL issues, and hello to partitioning support..

```
dataflow:>stream create foo --definition "http | log"
Created new stream 'foo'
dataflow:>stream deploy foo --properties "module.http.partitionKeyExpression=payload.length(), module.log.count=3"
Deployed stream 'foo'
dataflow:>runtime modules
╔═══════════════════════╤═══════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║Module Id / Instance Id│Unit Status│                                                Nb of Instances / Attributes                                                ║
╟───────────────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║foo.http               │ deployed  │                                                             1                                                              ║
╟┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈╢
║                       │           │working.dir = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.http-0-1029941279105341630                               ║
║foo.http-0             │ deployed  │     stdout = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.http-0-1029941279105341630/stdout_7418152489030773686.log║
║                       │           │     stderr = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.http-0-1029941279105341630/stderr_6712135003765518816.log║
║                       │           │        url = http://192.168.0.24:26527                                                                                     ║
╟───────────────────────┼───────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║foo.log                │ deployed  │                                                             3                                                              ║
╟┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈╢
║                       │           │working.dir = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.log-0-6993415172978486071                                ║
║foo.log-0              │ deployed  │     stdout = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.log-0-6993415172978486071/stdout_4907646679039008185.log ║
║                       │           │     stderr = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.log-0-6993415172978486071/stderr_3707678154246818248.log ║
║                       │           │        url = http://192.168.0.24:32334                                                                                     ║
╟┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈╢
║                       │           │working.dir = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.log-1-159341343714637846                                 ║
║foo.log-1              │ deployed  │     stdout = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.log-1-159341343714637846/stdout_1958939782508021448.log  ║
║                       │           │     stderr = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.log-1-159341343714637846/stderr_1209154932542084116.log  ║
║                       │           │        url = http://192.168.0.24:25585                                                                                     ║
╟┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┼┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈╢
║                       │           │working.dir = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.log-2-1097208467524381606                                ║
║foo.log-2              │ deployed  │     stdout = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.log-2-1097208467524381606/stdout_8232990717116463745.log ║
║                       │           │     stderr = /var/folders/ty/nnp8nms96w76mxhdpmbdgcx00000gn/T/foo.log-2-1097208467524381606/stderr_2492903738413791114.log ║
║                       │           │        url = http://192.168.0.24:41622                                                                                     ║
╚═══════════════════════╧═══════════╧════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

### CODE REVIEW

**Comment by markfisher** [comment]
Could this be refactored so that it's just a configuration-driven switch for the existing `LocalModuleDeployer` as opposed to a new SPI implementation?

**Comment by ericbottard** [comment]
They're quite different really. But could be two classes in the same "local" umbrella, with a switch in `LocalConfiguration` it that's what you're saying

**Comment by markfisher** [comment]
Right - what I'm thinking is the `LocalModuleDeployer` could delegate to those 2 classes. I realize they are very different, but from a SPI categorization perspective, we are typically mapping 1:1 from a SPI implementation to a target deployment environment. From a user's perspective, I'm wondering if it would be more intuitive to just think "local" but then have a switch for "singlenode" vs. "distributed".

**Comment by mbogoevici** [comment]
Maybe we should make this the one and only implementation for Local? As it is pretty clear that we do not want Local to be production ready, I don't see much reason to keep the in-process one, as well as explaining when to use one vs the other.

**Comment by ericbottard** [comment]
Marius has a point, although I'm not sure we want (even an evolution of) this new deployer to be considered for production. 
It is a better tool for development (no CL issues, partition support, although the other one could have supported it). It does not tail the module logs though, so a bit more cumbersome.
If it were me, I'd keep both but make this one the default (and use in-process for simple demos)

**Comment by markfisher** [comment]
Marius is saying the same thing. We absolutely do not want the current OR this Local deployer to be used in production. I think it's worth considering dropping the in-process one, but there is something nice about managing only a single process (e.g. ctrl-C once and no need to 'stream undeploy')

**Comment by ericbottard** [comment]
CTRL-C on the admin kills children with this one too.

**Comment by ericbottard** [comment]
I'm more concerned about the contrived way of getting hold of module logs (not the end of the world, but hinders productivity a bit)

**Comment by markfisher** [comment]
@ericbottard :) indeed it does... hmm

**Comment by mbogoevici** [comment]
@ericbottard Under no circumstances I meant using this in production. I would rather try to solve the problem of aggregating logging - maybe we should log to a single file by default and document that? As much as I like the flexibility - it just feels like we are making this too complex for the end user. My opinion of course.

**Comment by ericbottard** [comment]
Closing in favor of driven-by-switch version of "local" deployer

**Pull request closed without merging**
