### PR TITLE
Docker-compose based integration tests

### LINKED ISSUE #3272: Run AT's against docker-compose setup
@chrisjs commented on [Wed Aug 08 2018](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/issues/195)

Try running AT's against DF running in docker compose as we show in the getting started guide. This would help catch failures faster (i.e.: upgrading apps/tasks) and find things that may or may not be supported (i.e.: the `http | log` example  didn't work as no ports were exposed).

---

@chrisjs commented on [Mon Dec 10 2018](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/issues/195#issuecomment-445912142)

tabling this for now per discussion

---

@tzolov commented on [Thu Jun 06 2019](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/issues/195#issuecomment-499540620)

Depends on spring-cloud/spring-cloud-dataflow/issues/3265

### PR DESCRIPTION
**Pull request by tzolov**
- Use the palantir Rule to deploy the docker-compose.yml.
 - Add a custom (bintray) palantir maven repository.
 - Add DockerComposeIT integration tests. Use the Java Stream DSL and custom test utils.
 - Integration tests are disabled by default. Use the -Pfailfast profile to enable them.
 - Exclude the DataFlowClientAutoConfiguration for regular tests
 - Add README instructions to run the integration test.

 Resolves #3272

### CODE REVIEW

**Comment by sabbyanandan** [comment]
Let's skip the TODOs in the tests for now - we need to revisit to come up with a solution for Docker Compose.

**Comment by jvalkeal** [comment]
I can't really any of this running
```
./mvnw clean test-compile failsafe:integration-test -pl spring-cloud-dataflow-server -Pfailsafe

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jvalkealahti/repos/spring/spring-cloud-dataflow/spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/integration/test/DockerComposeIT.java:[136,77] cannot find symbol
  symbol:   method getName()
  location: variable s of type org.springframework.cloud.dataflow.rest.client.dsl.Stream

```

**Comment by jvalkeal** [comment]
Trying to run from sts:
```
com.palantir.docker.compose.execution.DockerExecutionException: 'docker-compose pull' returned exit code 1
The output was:
Invalid interpolation format for "image" option in service "dataflow-server": "springcloud/spring-cloud-dataflow-server:${DATAFLOW_VERSION:?DATAFLOW_VERSION is not set!}"
	at com.palantir.docker.compose.execution.Command.lambda$throwingOnError$13(Command.java:60)
	at com.palantir.docker.compose.execution.Command.execute(Command.java:50)
	at com.palantir.docker.compose.execution.DefaultDockerCompose.pull(DefaultDockerCompose.java:72)
	at com.palantir.docker.compose.execution.DelegatingDockerCompose.pull(DelegatingDockerCompose.java:35)
	at com.palantir.docker.compose.execution.RetryingDockerCompose.pull(RetryingDockerCompose.java:22)
	at com.palantir.docker.compose.DockerComposeRule.before(DockerComposeRule.java:140)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

```

**Comment by jvalkeal** [comment]
right my local version is:
```
$ docker-compose -v
docker-compose version 1.18.0, build 8dd22a9
```
so maybe because of that.

**Comment by jvalkeal** [comment]
With docker-compose 1.24.0 containers actually start but there's new failures:
```
java.lang.IllegalStateException: The cluster failed to pass a startup check: Encountered an exception: java.lang.IllegalArgumentException: No internal port '9393' for container 'dataflow-server': com.palantir.docker.compose.connection.Container$$Lambda$64/71217763@50887e53
	at com.palantir.docker.compose.connection.Container.lambda$port$11(Container.java:91)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.palantir.docker.compose.connection.Container.port(Container.java:91)
	at com.palantir.docker.compose.connection.Container.portIsListeningOnHttp(Container.java:58)
	at com.palantir.docker.compose.connection.Container.portIsListeningOnHttpAndCheckStatus2xx(Container.java:49)
	at com.palantir.docker.compose.connection.waiting.HealthChecks.lambda$toRespond2xxOverHttp$26(HealthChecks.java:32)
	at com.palantir.docker.compose.connection.waiting.ClusterHealthCheck.lambda$transformingHealthCheck$21(ClusterHealthCheck.java:42)
	at com.palantir.docker.compose.connection.waiting.ClusterWait.lambda$weHaveSuccess$23(ClusterWait.java:57)
	at com.jayway.awaitility.core.CallableCondition$ConditionEvaluationWrapper.call(CallableCondition.java:99)
	at com.jayway.awaitility.core.CallableCondition$ConditionEvaluationWrapper.call(CallableCondition.java:85)
	at com.jayway.awaitility.core.ConditionAwaiter$1.run(ConditionAwaiter.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at com.palantir.docker.compose.connection.waiting.ClusterWait.waitUntilReady(ClusterWait.java:50)
	at com.palantir.docker.compose.DockerComposeRule.lambda$before$0(DockerComposeRule.java:155)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.palantir.docker.compose.DockerComposeRule.before(DockerComposeRule.java:155)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

```
What's even worse is that DockerComposeRule doesn't clean up running containers so I was left 9 containers to clean up manually.

**Comment by jvalkeal** [comment]
`dataflow-server` failed to start as `mysql` wasn't yet running. It's conceptually wrong as in docker compose you can only control start ordering, not if dependant container is ready.

**Comment by tzolov** [comment]
@jvalkeal 
- To resolve the compilation error above you need build the `scdf-rest` project first (because there some Java DSL changes there) before running the integration tests. eg. 
```
./mvnw clean install -DskipTests
./mvnw clean test-compile failsafe:integration-test -pl spring-cloud-dataflow-server -Pfailsafe
```

- Regarding the `mysql` service order, i've just committed  (1bb50e07c2be6b3d3a79a86c18c1694f7b7173dd) an additional condition that should make the test wait until mysql is up before the tests are run.  Although not a general solution for the docker-compose service ordering problem i believe this might be enough for this test?  Please give it a try.

**Comment by jvalkeal** [comment]
016831edaa8a3b1dfe88b4e15505d4f3334bd837 didn't work, all containers are still left behind when dataflow fails.

**Comment by tzolov** [comment]
Ok, the 3011974 should clear the leftover containers.

**Comment by tzolov** [comment]
Because of the newly added wai-for-it.sh script, you need fresh build of the Skipper and dataflow docker images. 
- On skipper side. Get the https://github.com/spring-cloud/spring-cloud-skipper/pull/878 PR and build the docker image locally:
```
./mvnw clean install -DskipTests
./mvnw -pl spring-cloud-skipper-server dockerfile:build
```

- Then on the dataflow side:
```
./mvnw clean install -DskipTests
./mvnw -pl spring-cloud-dataflow-server docker:build
./mvnw clean test-compile failsafe:integration-test -pl spring-cloud-dataflow-server -Pfailsafe
```

**Comment by jvalkeal** [comment]
finally looking good, merging

**Pull request merged**
