### PR TITLE
Support deploying docker apps in local data flow server

### LINKED ISSUE #695: Could not deploy docker app resources
When using app resource URI as docker URL, the stream deployment fails as it could not load the docker resource file.

To reproduce:

> dataflow:>app register --type source --name time --uri docker:springcloudstream/time-source-kafka:latest
> dataflow:>app register --type sink --name log --uri docker:springcloudstream/log-sink-kafka:latest
> dataflow:>stream create a1 --definition "time | log" --deploy

Following exception is thrown:

```
java.lang.RuntimeException: Exception trying to list configuration properties for application ServletContext resource [/docker:springcloudstream/log-sink-kafka:latest]
    at org.springframework.cloud.dataflow.configuration.metadata.ApplicationConfigurationMetadataResolver.listProperties(ApplicationConfigurationMetadataResolver.java:123) ~[spring-cloud-dataflow-configuration-metadata-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.qualifyParameters(StreamDeploymentController.java:267) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deployStream(StreamDeploymentController.java:243) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deploy(StreamDeploymentController.java:186) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RE
...
...
Caused by: java.lang.IllegalArgumentException: File must exist
    at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:67) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:51) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:95) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:65) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.configuration.metadata.ApplicationConfigurationMetadataResolver.listProperties(ApplicationConfigurationMetadataResolver.java:87) ~[spring-cloud-dataflow-configuration-metadata-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Add docker resource loader into DelegatingResourceLoader bean for `local` data flow server configuration

This resolves #695

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
The corresponding `local` deployer fix is made [here](https://github.com/spring-cloud/spring-cloud-deployer-local/pull/7).

Steps to deploy `docker` app from SCDF is to pass (1) docker environment properties and (2) app properties as stream `deployment` properties as:

```
dataflow:>stream create a1 --definition "time | log"
Created new stream 'a1'
dataflow:>stream deploy a1 --properties "app.*.DOCKER_TLS_VERIFY=1,app.*.DOCKER_HOST=tcp://192.168.99.100:2376,app.*.DOCKER_CERT_PATH=/Users/test/.docker/machine/machines/default,app.*.DOCKER_MACHINE_NAME=default,app.time.server.port=9191,app.log.server.port=9292"
Deployment request has been sent for stream 'a1'
dataflow:>
```

**Comment by ilayaperumalg** [comment]
Rebased.

**Comment by ericbottard** [comment]
On a more general note, how do we expect users to use middleware services such as rabbit, etc?

Seems at the minimum we should automate the LINKing process between deployed apps and a set of other containers (in the same way the CF deployer has a list of CF services to bind to apps for example)

**Comment by ilayaperumalg** [comment]
They would have to set the required host configurations as `deployment` properties as that seems to be the only way to set the `environment` variables for `docker run`

**Comment by ericbottard** [comment]
Are you saying app properties aren't passed? (this seemed to be implied by one of your earlier comments)? (not that they should be used for this particular usecase)

**Comment by ilayaperumalg** [comment]
no,  all the app properties that are set via `definition` as well as `deployment` properties are passed as `environment` option for `docker run`. What I meant was, user has to pass the host configuration via those properties.

**Comment by ilayaperumalg** [comment]
Closing this now. Will re-address the `docker` deployment post GA.

**Pull request closed without merging**
