### PR TITLE
Fix search pageable query in StreamDef List

### LINKED ISSUE #1598: REST: Stream Definition List - Pagination with Search Filter gives incorrect results
When using a filter list correctly shown filtered entries but original pagination number is still reflected. i.e if you have 30 defs, filter gives only one, there should be on one page.

This is depended on by https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/257

See also: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java#L201

### PR DESCRIPTION
**Pull request by ilayaperumalg**
Resolves #1598

### CODE REVIEW

**Comment by jvalkeal** [comment]
Yeah this didn't fix it. It simply broke pagination with filtering so that we don't get second page anymore.

```
app import --uri http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/spring-cloud-stream-app-descriptor/Bacon.RELEASE/spring-cloud-stream-app-descriptor-Bacon.RELEASE.rabbit-apps-maven-repo-url.properties

stream create --name foostream1 --definition "time|log"
stream create --name foostream2 --definition "time|log"
stream create --name foostream3 --definition "time|log"
stream create --name foostream4 --definition "time|log"
stream create --name foostream5 --definition "time|log"
stream create --name foostream6 --definition "time|log"
stream create --name foostream7 --definition "time|log"
stream create --name foostream8 --definition "time|log"
stream create --name foostream9 --definition "time|log"
stream create --name foostream10 --definition "time|log"
stream create --name foostream11 --definition "time|log"
stream create --name foostream12 --definition "time|log"
stream create --name foostream13 --definition "time|log"
stream create --name foostream14 --definition "time|log"
stream create --name foostream15 --definition "time|log"
stream create --name foostream16 --definition "time|log"
stream create --name foostream17 --definition "time|log"
stream create --name foostream18 --definition "time|log"
stream create --name foostream19 --definition "time|log"
stream create --name foostream20 --definition "time|log"
stream create --name foostream21 --definition "time|log"
stream create --name foostream22 --definition "time|log"
stream create --name foostream23 --definition "time|log"
stream create --name foostream24 --definition "time|log"
stream create --name foostream25 --definition "time|log"
stream create --name foostream26 --definition "time|log"
stream create --name foostream27 --definition "time|log"
stream create --name foostream28 --definition "time|log"
stream create --name foostream29 --definition "time|log"
```
Filtering with `foostream1` should return 11 items and it now thinks there's only 10 items.
ui-pagination-bug-1

With this request `http://localhost:9393/streams/definitions?page=0&search=foostream1&size=10&sort=DEFINITION_NAME,DEFINITION,ASC` returns

```
"page":{"size":10,"totalElements":10,"totalPages":1,"number":0}
```

I pushed my [branch](https://github.com/jvalkeal/spring-cloud-dataflow/commit/6db60c7be58a3fb6225ba43e85fea89bbd263032) where I originally worked on this and there's a new test in it. Test may not be fully ok as I wasn't able to fix this issue but test shows how pagination with filtering should be tested.

**Comment by jvalkeal** [comment]
Doesn't matter but there was also errors in logs
```
java.lang.IllegalArgumentException: fromIndex(20) > toIndex(0)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1006) ~[na:1.8.0_121]
	at java.util.ArrayList.subList(ArrayList.java:996) ~[na:1.8.0_121]
	at java.util.Collections$UnmodifiableRandomAccessList.subList(Collections.java:1400) ~[na:1.8.0_121]
	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.list(StreamDefinitionController.java:211) ~[spring-cloud-dataflow-server-core-1.2.3.BUILD-SNAPSHOT.jar!/:1.2.3.BUILD-SNAPSHOT]
```

**Comment by ilayaperumalg** [comment]
@jvalkeal Pushed an update here. This update seems to have fixed the issue. I also added the tests you had to test this bug. 

The original problem was with the return value of `search(Pageable)` where we always updated the `totalCount` of the returned result for that specific page while this `totalCount` needs to be of the entire result for the given search query. I added an explicit query to update the correct `totalCount` and the issue seems to be fixed. Let me know how it goes from your end.

**Comment by jvalkeal** [comment]
lgtm, merging

**Comment by jvalkeal** [comment]
merged per https://github.com/spring-cloud/spring-cloud-dataflow/commit/f6f384d7110deff23da9d72d6c9910229655e867

**Pull request closed without merging**
