### PR TITLE
stream skipper update to use same prop format as stream skipper deploy

### LINKED ISSUE #1750: Properties passed to `stream skipper update` should be same format as non-skipper case
Currently we update the stream by passing in a 'skipper' style YAML document
```
stream skipper update ticktock --yamlFile log-level-change.yml
```
Where `log-level-change.yml` is
```
log:
  version: 1.1.1.RELEASE
  spec:
    applicationProperties:
      server.port: 9999
      endpoints.sensitive: false
      log.level: ERROR
    deploymentProperties:
      memory: 4096m
```
We should not make the user aware of this underlying format since they are used to a specific way to set application and deployer properties when deploying a stream without skipper..

```
stream deploy ticktock --properties="app.time.trigger.delay=5,deployer.time.memory=2G"
```

We should not require the user to create a 'skipper' flavored yaml file to specify the app or deployment properties.  A more SCDF centric YAML file format for this would look like
```
stream skipper update ticktock --yamlFile log-level-change.yml
```
Where `log-level-change.yml` is
```
app:
  log:
    version: 1.1.1.RELEASE
    server.port: 9999
    endpoints.sensitive: false
    log.level: ERROR
deployer
  log:
     memory: 4096m
```

The translation to pass these properties to skipper using `log.spec.applicationProperties` format will need to be implemented.  Note, that `version` isn't really an application property , maybe it needs to be handled differently.
```
versions:
  log: 1.1.1.RELEASE
app:
  log:
    server.port: 9999
    endpoints.sensitive: false
    log.level: ERROR
deployer:
  log:
     memory: 4096m
```

### PR DESCRIPTION
**Pull request by markpollack**
Minor integration testing using
```
app import --uri http://bit.ly/Bacon-RELEASE-stream-applications-rabbit-maven
stream create --name ticktock --definition "time | log"
stream skipper update --name ticktock --properties "version.log=1.1.0.RELEASE"
```

See added test for more involved update changes.

Fixes #1750

### CODE REVIEW

**Comment by markpollack** [comment]
Property metadata for the new release version, if applicable, should be used.

**Comment by sabbyanandan** [comment]
The create, deploy, update, and list cycle worked as expected. 👍

**Comment by jvalkeal** [comment]
I have one failing test
```
Tests in error: 
  verifyUpgradeStream(org.springframework.cloud.dataflow.server.service.impl.DefaultStreamServiceTests): Could not find stream definition named test2
```

**Comment by jvalkeal** [comment]
This may not be part of this PR but now that you're claiming - "stream skipper update to use same prop format as stream skipper deploy", that's not exactly true as
```
dataflow:>stream deploy --name foostream --properties "version.time=1.2.1.BUILD-SNAPSHOT"
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Only deployment property keys starting with 'app.' or 'deployer.' allowed, got 'version.time'
```
while update works fine after you have stream deployed
```
dataflow:>stream skipper deploy --name foostream
Deployment request has been sent for stream 'foostream'

dataflow:>stream skipper update --name foostream --properties "version.time=1.2.1.BUILD-SNAPSHOT"
Update request has been sent for stream 'foostream'
```

**Comment by markpollack** [comment]
good point.  `version` should become a new top level property in the new skipper commands.  So playing out a scenario
```
app register --name log --type sink --uri maven://org.springframework.cloud.stream.app:log-sink-rabbit:1.2.0.RELEASE --default
app register --name log --type sink --uri maven://org.springframework.cloud.stream.app:log-sink-rabbit:1.2.1.RELEASE


app list log
================
version       | name | type  | default | url
==========================================
1.2.0.RELEASE |  log |  sink   yes     |
1.2.1.RELEASE |  log |  sink   no      |


stream create ticktock --definition "time | log"

stream skipper deploy --name ticktock --properties "version.log=1.2.1.RELEASE"

// check 1.2.1 against AppRegistry

app register --name log --type sink --uri maven://org.springframework.cloud.stream.app:log-sink-rabbit:1.2.2.RELEASE

stream skipper update --name ticktock --properties "version.log=1.2.2.RELEASE"
```

**Comment by markpollack** [comment]
I fixed the tests, somewhat awkwardly as there was a downcast involved and more use of integration testing + `@MockBean` than seems necessary.

Will create a issue to revisit the unit/integration tests of `DefaultStreamService` and to add `version` as a top level property in Skipper commands as shown above.

**Comment by markpollack** [comment]
merged as 9ac48ed73e8c938a8393a5ef2e060b347850a78f  Created issues #1759 and #1760

**Pull request closed without merging**
