### PR TITLE
Updated tooltip for metrics

### LINKED ISSUE #1391: Metrics screenshots include wrong tooltip info
As a developer, I'd like to fix the metrics screenshot with currently supported assets in the tool-tip. (port, guid, ip, and host don't apply anymore)

image

### PR DESCRIPTION
**Pull request by trisberg**
Resolves #1391

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
From #1391, 

> (port, guid, ip, and host don't apply anymore)

I guess @sabbyanandan meant `group` as we use `guid` in the metrics.

**Comment by ilayaperumalg** [comment]
LGTM, will merge once the above is confirmed.

**Comment by sabbyanandan** [comment]
@ilayaperumalg Yes, `GUID` is a _mandatory_ requirement. Sorry for the confusion.

**Comment by ilayaperumalg** [comment]
Rebased and merged as ea5bacc454c2e47a4308c187d127d3cdbcd696ba

**Pull request closed without merging**
