### PR TITLE
Add additional env vars to deployed module

### PR DESCRIPTION
**Pull request by dsyer**
User can specify additional command line args like this in the
local deployer app:

```
deployer:
  local:
    sharedArgs:
      includes: org.springframework.cloud:spring-cloud-starter-config:1.1.0.BUILD-SNAPSHOT
      spring.application.name: ${module.label}
      spring.cloud.config.uri: http://localhost:8888
```

Then all modules are launched with "includes" on the classpath
and enough information to bootstrap the config client.

The "includes" is a feature of the module launcher, and it is a
comma separated list, so we have to be careful to merge
module and deployment specific arguments with the same name.

### CODE REVIEW

**Comment by ericbottard** [comment]
Should these shared args really apply only to the local deployer? Also, note that those args *in fine* apply to the **module**, not really to the deployer

**Comment by dsyer** [comment]
They are "shared" by all modules, hence the name. It's not for the local deployed right now, but I suppose a similar feature might make sense.

**Comment by ericbottard** [comment]
Also, just to clarify, know that the same outcome may be attained by using module deployment properties:

`stream deploy foo --properties "module.*.includes=xxx,module.*.spring.cloud.config.uri=yy"` *etc.*

**Comment by dsyer** [comment]
It's the same outcome as far as the module is concerned. But for users it's completely different (they don't have to type that includes mumbo jumbo for every stream deployment).

**Comment by dsyer** [comment]
Ping. Can we merge this or something like it? Even if we don't support includes any more (boo) we can expect that this feature might be useful (it's not related directly to includes).

**Comment by markpollack** [comment]
Didn't realize this was assigned to me.  BTW, the spot to support for adding a jar to the classpath seems to be a natural fit for a boot loader.  While I am not in having transitive or excludes functionality, would seem a boot loader would be the spot for any more sophisticated implementations that change the classpath at runtime.

**Comment by ericbottard** [comment]
Irrespective of whether we merge this as-is or not, could we consider adding this functionality to _any_ deployer (_i.e._ not make the keys deployer.**local**.sharedArgs but just deployer.sharedArgs)

**Comment by markfisher** [comment]
If at all possible, we should defer this feature until we switch to the generic deployer and figure out the `ModuleLauncher

**Comment by markpollack** [comment]
Sorry for such a long delay.  I created https://github.com/spring-cloud/spring-cloud-deployer/issues/70 and also https://github.com/spring-cloud/spring-cloud-dataflow/issues/661 and https://github.com/spring-cloud/spring-cloud-dataflow/issues/662 to add env-var support now that we are based on AppDeployer.   

It isn't clear to me if there is a Boot Launcher implementation that would provide the same functionality as the ModuleLauncher for including other jars at runtime.  If there is a Boot feature for this, we can expose it in dataflow/deployers.

**Pull request closed without merging**
