### PR TITLE
Remove remains of ctr app name

### LINKED ISSUE #4273: Remove defunc composedTaskRunnerName task launch shell option
When ctr app went from registered app to server setting, this option were left behind into shell and is no use today.

### PR DESCRIPTION
**Pull request by jvalkeal**
- Remove ctr app from task shell launch
- Remove its remains from TaskTemplate and tests
- Fixes #4273

### CODE REVIEW

**Comment by cppwfs** [comment]
Shouldn't we deprecate this first?   Thoughts?

**Comment by jvalkeal** [comment]
It should have been removed at a same time when ctr app moved from being a registered app. That option in a shell doesn't do anything.

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
Rebased Merged.

**Pull request closed without merging**
