### PR TITLE
Changes in Schema scripts

### LINKED ISSUE #1954: Include migration and jpa-scripts in the DB Initializer
As a developer, I'd like to make changes to the DBInitializer to include migration and the JPA schemas.

1) Remove [ddl-auto: create](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-starter-dataflow-server-local/src/main/resources/dataflow-server.yml#L24-L26) from the server yaml.

2) Add support to include [migration-scripts](https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-server-core/src/main/resources/migration/1.3.x) and [jpa-schema](https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-server-core/src/main/resources/schema-jpa) to the populator.
2.1) Verify the new schema folders are included in the pom.xml
2.2) Verify whether the [note in the docs](https://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#configuration-rdbms) is necessary

3) Run 1.2.x and 1.3.x servers to verify the script execution.

### PR DESCRIPTION
**Pull request by viniciusccarvalho**
- Refactored scripts locations to a hierarchical folder structure
- Removed hibernate ddl generation
- Added jpa.sql to create tables for JPA Entities
- Forcing ddl-auto to none even for in memory dbs

Fixes #1954

### CODE REVIEW

**Comment by sabbyanandan** [comment]
As noted in the issue description (#1954), perhaps it is safe to remove the [NOTE](https://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#configuration-rdbms) from the ref. guide re: migration?

**Comment by ghillert** [comment]
Just a minor UX note regarding DB configuration: In Skipper I did NOT have to configure `driver-class-name: oracle.jdbc.driver.OracleDriver` - In SCDF it is a MUST as otherwise SCDF still tries to use H2. 

Created https://github.com/spring-cloud/spring-cloud-dataflow/issues/1957

**Comment by ghillert** [comment]
@sabbyanandan I created https://github.com/spring-cloud/spring-cloud-dataflow/issues/1958

**Comment by ghillert** [comment]
LGTM create the 2 referenced issues above. Merged with commit 61a206c80fd7c8a3c788910fdc79dc941c0a9f84

**Pull request closed without merging**
