### PR TITLE
Fixes #3558; Memory usage graph for application grafana dashboard to …

### LINKED ISSUE #3558: Application Grafana Dashboard Memory Graph is wrong
On the grafana dashboard for **Application**, the memory usage graph is displaying the average.  I believe this is wrong.  Instead, this should be the sum of all memory bytes for that application.

### PR DESCRIPTION
**Pull request by allanmoso**
…perform sum instead of average.

fixes #3558

### CODE REVIEW

**Comment by tzolov** [comment]
Thanks for the fix @allanmoso.  Change LGTM

**Comment by tzolov** [comment]
@allanmoso could you please rebase your PR on to of the upstream/master ? Let me know if you need help

**Comment by allanmoso** [comment]
@tzolov  Checks are still running but it should be rebased on top of upstream/master now.

**Comment by tzolov** [comment]
Thanks @allanmoso !
Merged at 17787328e59c51292f70decdee05e7f2fb5ad369

**Pull request closed without merging**
