### PR TITLE
Use stream/task descriptions in shell

### PR DESCRIPTION
**Pull request by sylank**
This PR contains the CLI part of the stream and task definition description feature:

As stream creator, I should be able to provide a description for a stream & task definition.
This can make it easy for a new joiner to know what is the purpose of the stream and task.

Resolves: #3430

### CODE REVIEW

**Comment by sabbyanandan** [comment]
Nicely done, @sylank! 🎖

**Comment by sylank** [comment]
I have just created PR about the front-end part of the feature:
https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/1273

**Comment by jvalkeal** [comment]
Don't have anything to complain, I'm going to merge as is, thanks a lot!

**Comment by jvalkeal** [comment]
Squashed and merged per bf830a23053fa19c63a574904d0d4f23eff7a72f

**Pull request closed without merging**
