### PR TITLE
Now supports the out of order deletion of CTR and its child tasks

### PR DESCRIPTION
**Pull request by cppwfs**
resloves #3655

### CODE REVIEW

**Comment by jvalkeal** [comment]
I think this is not enough, created
```
timestamp
t1:timestamp && t2:timestamp
t3:timestamp && t4:timestamp
```
and then you get error when trying to delete those all:
```
2019-11-27 14:05:18.040  INFO 10527 --- [nio-9393-exec-5] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2019-11-27 14:05:18.041  INFO 10527 --- [nio-9393-exec-6] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2019-11-27 14:05:18.043  INFO 10527 --- [nio-9393-exec-7] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task3-t3. Did not find a previously launched task to destroy.
2019-11-27 14:05:18.043  INFO 10527 --- [nio-9393-exec-8] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task2-t2. Did not find a previously launched task to destroy.
2019-11-27 14:05:18.043  INFO 10527 --- [nio-9393-exec-4] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task2-t1. Did not find a previously launched task to destroy.
2019-11-27 14:05:18.045  INFO 10527 --- [nio-9393-exec-2] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task1. Did not find a previously launched task to destroy.
2019-11-27 14:05:18.048  WARN 10527 --- [nio-9393-exec-6] o.s.c.d.s.s.i.DefaultTaskDeleteService   : Attempted delete on a child task that is currently being deleted

org.springframework.orm.ObjectOptimisticLockingFailureException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: HikariProxyPreparedStatement@1835855803 wrapping prep109: delete from task_definitions where definition_name=? {1: 'task3-t3'}; nested exception is org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: HikariProxyPreparedStatement@1835855803 wrapping prep109: delete from task_definitions where definition_name=? {1: 'task3-t3'}
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:340)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:538)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:744)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:712)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:631)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy206.deleteById(Unknown Source)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.destroyTask(DefaultTaskDeleteService.java:364)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.destroyChildTask(DefaultTaskDeleteService.java:360)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.lambda$1(DefaultTaskDeleteService.java:341)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.deleteTaskDefinition(DefaultTaskDeleteService.java:335)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService.deleteTaskDefinition(DefaultTaskDeleteService.java:305)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskDeleteService$$FastClassBySpringCGLIB$$13444684.invoke(<generated>)
```

**Comment by jvalkeal** [comment]
It's slightly better as things actually get's deleted but I'm still seeing error in UI.

ctr-delete-error

Server logs while this happened:
```
2019-11-28 14:53:25.412  INFO 31933 --- [nio-9393-exec-7] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2019-11-28 14:53:25.413  WARN 31933 --- [nio-9393-exec-7] o.s.c.d.s.s.i.DefaultTaskDeleteService   : Attempted delete on a child task that is currently being deleted
2019-11-28 14:53:25.413  INFO 31933 --- [io-9393-exec-10] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task2-t1. Did not find a previously launched task to destroy.
2019-11-28 14:53:25.415  INFO 31933 --- [nio-9393-exec-9] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task2-t2. Did not find a previously launched task to destroy.
2019-11-28 14:53:25.416  INFO 31933 --- [nio-9393-exec-1] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2019-11-28 14:53:25.416  INFO 31933 --- [nio-9393-exec-3] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task3-t3. Did not find a previously launched task to destroy.
2019-11-28 14:53:25.416  WARN 31933 --- [nio-9393-exec-1] o.s.c.d.s.s.i.DefaultTaskDeleteService   : Attempted delete on a child task that is currently being deleted
2019-11-28 14:53:25.418  INFO 31933 --- [nio-9393-exec-4] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task1. Did not find a previously launched task to destroy.
2019-11-28 14:53:25.421  INFO 31933 --- [nio-9393-exec-7] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task2. Did not find a previously launched task to destroy.
2019-11-28 14:53:25.421  INFO 31933 --- [nio-9393-exec-1] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task3-t4. Did not find a previously launched task to destroy.
2019-11-28 14:53:25.427  WARN 31933 --- [nio-9393-exec-5] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request: Could not find task definition named task3-t4
2019-11-28 14:53:25.428  WARN 31933 --- [nio-9393-exec-5] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.cloud.dataflow.server.repository.NoSuchTaskDefinitionException: Could not find task definition named task3-t4]
2019-11-28 14:53:25.428  INFO 31933 --- [nio-9393-exec-1] o.s.c.d.s.s.i.DefaultTaskDeleteService   : TaskLauncher.destroy not invoked for task task3. Did not find a previously launched task to destroy.
```
I'm not sure if this is a backend or frontend issue while this delete happens. cc @oodamien. If it's a frontend issue then I'm ready to merge and create a UI issue.

**Comment by cppwfs** [comment]
In this case the UI will have to eat the 404 on deletes, because it is trying to delete CTR child task definitions  that have been deleted because the parent has been deleted.  

The only other option would be to add a new method to API that would take a list of task definition names and try to sort out the proper order of deletes.

**Comment by jvalkeal** [comment]
Merged per a09000edef57c46263cebbf87d47bcb383b2b766

**Pull request closed without merging**
