### PR TITLE
Added documentation about a new CF connection property (Fixes gh-3576).

### PR DESCRIPTION
**Pull request by dbahatSAP**
Resolves the documentation part of https://github.com/spring-cloud/spring-cloud-dataflow/issues/3576

### CODE REVIEW

**Comment by sabbyanandan** [comment]
@tzolov: This relates to the CF-deployer change via: https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/317.

**Comment by tzolov** [comment]
@sabbyanandan @dbahatSAP i believe that this change would need to be applied to the Skipper side as well? I guess here: https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-autoconfigure/src/main/java/org/springframework/cloud/skipper/server/autoconfigure/CloudFoundryPlatformAutoConfiguration.java#L93

**Comment by dbahatSAP** [comment]
Yes. Here's the skipper change: https://github.com/spring-cloud/spring-cloud-skipper/pull/922

**Comment by tzolov** [comment]
Rebased, squashed and merged at 25bdb84aa6ac76c91f10fa5e8b9a468291fc997d

**Pull request closed without merging**
