### PR TITLE
prevents child tasks from being created if apps dont exist

### LINKED ISSUE #1669: Subtasks are created even when overall task definition is invalid
Version: 1.2.4.RELEASE
What happens: Subtasks are created, and parent is not
What should happen: When an overall task definition is invalid, subtasks should not be created
Repro steps: 

1. In SCS: task create --name foo --definition "app1 && app2 'COMPLETED' -> $END"
2. Observe error message that no app called $END is registered
3. In SCS: task list
4. Observe foo-app1 and foo-app2 in list

### PR DESCRIPTION
**Pull request by cppwfs**
in the case where a user enters a valid composed task definition but contains an app that does not exist, we should not create child task definitions until we have validated that all task apps are present.  For example task create bar --definition "AAA && BBB  'COMPLETED' -> $END" should not create AAA nor BBB since $END does not exist.

resolves #1669

### CODE REVIEW

**Comment by mminella** [comment]
Am I missing something or how are we handling the concurrent aspect of the server?  I don't see any synchronization around this operation via a transaction/etc.

**Comment by cppwfs** [comment]
Not sure Data Flow handles concurrent issues as of yet.  I'm not seeing `@Transactional` annotations for example.

**Comment by mminella** [comment]
But this type of things is exactly where that arises.  We probably have a similar issue when deploying streams.  If a stream of 5 apps starts to deploy and then an app is deleted while it's happening, do we undeploy the others?  This issue is about the creation of an atomic unit of work.  This fix doesn't do that IMHO.

**Comment by cppwfs** [comment]
I think what you are describing is valid however, this is not what this PR is meant to address per se'.   The key here is that someone creates a CTR with an invalid task.   for example `AAA && BBB && BAD`.  Without this bug fix `FOO-AAA` and `FOO-BBB` are created, but then Data Flow fails trying to create 'FOO-BAD`.  i.e. we should check to see if AAA, BBB and BAD are there first before even beginning the process.

**Comment by cppwfs** [comment]
Closing this PR as it does not resolve all the scenarios.  Look at https://github.com/spring-projects/spring-retry

**Comment by mminella** [comment]
I'm closing this until @cppwfs finishes his work with Spring Retry.

**Pull request closed without merging**
