### PR TITLE
URLResource path can have version

### LINKED ISSUE #2082: Url versioning doesn't work with skipper
```
dataflow:>app register --name log --type sink --uri http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/log-sink-rabbit/1.1.0.RELEASE/log-sink-rabbit-1.1.0.RELEASE.jar
dataflow:>app register --name time --type source --uri http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/time-source-rabbit/1.1.1.RELEASE/time-source-rabbit-1.1.1.RELEASE.jar
dataflow:>app register --name log --type sink --uri http://repo.spring.io/libs-release-local/org/springframework/cloud/stream/app/log-sink-rabbit/1.1.1.RELEASE/log-sink-rabbit-1.1.1.RELEASE.jar
dataflow:>stream create --name foostream --definition "time|log"

dataflow:>stream deploy --name foostream
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: URL resource with version as part of its path is not supported.


java.lang.IllegalArgumentException: URL resource with version as part of its path is not supported.
	at org.springframework.util.Assert.isTrue(Assert.java:92) ~[spring-core-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.cloud.dataflow.registry.support.ResourceUtils.getUrlResourceWithoutVersion(ResourceUtils.java:61) ~[spring-cloud-dataflow-registry-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.registry.support.ResourceUtils.getResourceWithoutVersion(ResourceUtils.java:204) ~[spring-cloud-dataflow-registry-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.createDependentPackage(SkipperStreamDeployer.java:340) ~[spring-cloud-dataflow-server-core-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.createDependentPackages(SkipperStreamDeployer.java:313) ~[spring-cloud-dataflow-server-core-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.createPackage(SkipperStreamDeployer.java:305) ~[spring-cloud-dataflow-server-core-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.createPackageForStream(SkipperStreamDeployer.java:280) ~[spring-cloud-dataflow-server-core-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.dataflow.server.stream.SkipperStreamDeployer.deployStream(SkipperStreamDeployer.java:201) ~[spring-cloud-dataflow-server-core-1.4.0.BUILD-SNAPSHOT.jar!/:1.4.0.BUILD-SNAPSHOT]

```

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Remove assertion on not expecting `version` as part of the URL path
 - Update test

Resolves #2082

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Depending on the criticality of this issue, we can triage this for RC or post RC.

**Comment by jvalkeal** [comment]
Last week I quickly tried these exact same changes and everything looked ok. Wasn't sure if those asserts were put in place to just guard something bad happening later or somewhere else.

**Comment by markpollack** [comment]
I looked and nothing rings a bell, perhaps I went back later to update the regex to be a bit more robust.

However, in the case of skipper mode, we may want to ensure semver semantics on the version number since we enforce that on the skipper side.  In other words, fail fast in SCDF checking for semver.

**Comment by ilayaperumalg** [comment]
I will double check on this from the skipper side to see if it breaks anything during semver semantics verification.

**Comment by ilayaperumalg** [comment]
I checked this on Skipper side and it looks good (at the PackageService - validating the version from upload request).

**Comment by jvalkeal** [comment]
Do we have consensus? If so I can merge this.

**Comment by jvalkeal** [comment]
merged per 15095222f7693b04573ae5aae678e0e991367758

**Pull request closed without merging**
