### PR TITLE
Use a prefix for DataFlowServerProperties

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes spring-cloud/spring-cloud-dataflow#417

### CODE REVIEW

**Comment by markfisher** [comment]
`AdminProperties` is about to be renamed when this is merged: https://github.com/spring-cloud/spring-cloud-dataflow/pull/416

Perhaps we should wait? Also, as you might be anticipating based on the prefix name you chose, the properties that are currently defined might move to the `spring-cloud-deployer` layer once we make that shift.

**Comment by ericbottard** [comment]
Yes, I know. And to add to the confusion, the current set of 3 properties are actually used by the _launcher_ on the launched module side.
I wouldn't mind waiting if this wasn't needed by https://github.com/spring-cloud/spring-cloud-dataflow-admin-cloudfoundry/pull/23 (which for some reason did not appear in the timeline of _this_ PR)

**Comment by ericbottard** [comment]
Rebased

**Comment by ilayaperumalg** [comment]
LGTM, rebased, modified the commit description to read `DataFlowServerProperties` and merged as fb36d9c08cdd8cca5a77370df397ee4607c3e8ce

**Pull request closed without merging**
