### PR TITLE
3994; added anonymous authentication for resolving metadata

### LINKED ISSUE #3994: Anonymous authentication for docker registries
**Problem description:**
When DataFlow Server pulls metadata from a docker registry there are a few authentication mechanisms provided in DefaultContainerImageMetadataResolver. Our internal repository (and many public) have anonymous read access. This is not currently supported.

**Solution description:**
Altering the authentication process to not insert authentication headers if no authentication-type is selected.

### PR DESCRIPTION
**Pull request by jameswynn**
* New anonymous authorizer
* Minimum modifications to related files
* Additional tests

Resolves #3994

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jameswynn Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4000)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4000) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by jameswynn** [comment]
Signed the CLA.

**Comment by pivotal-issuemaster** [comment]
@jameswynn Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4000)!

**Comment by sabbyanandan** [comment]
@jameswynn: Thanks for your contribution! @tzolov will have a look soon.

**Comment by tzolov** [comment]
Thanks @jameswynn !
Merged at de4969d976850b1feeecfd9569066f5f0531f4fd

**Pull request closed without merging**
