### PR TITLE
Added exclusion for jackson in the common-security-config-web depende…

### LINKED ISSUE #1930: Exclude Jackson from Spring Cloud Common Security dependency
Due to `Spring Cloud Common Security` we pull in an old `jackson-core-asl` `1.9.13`. We should exclude that.

see also https://github.com/spring-cloud/spring-cloud-dataflow/issues/1922

### PR DESCRIPTION
**Pull request by cppwfs**
…ncy.

resolves #1930

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@cppwfs @ghillert Could you share the issue you ran into when using this dependency?

**Comment by cppwfs** [comment]
@ilayaperumalg I didn't see any issues with it other than it was an older version of Jackson in the dependency tree.  @ghillert may have seen an issue, since he reported it.

**Comment by ghillert** [comment]
@ilayaperumalg No functional issue ... no reason to include an old version of Jackson though. The problem is that due to the different artifact id, but dependencies get included in the resulting JAR.

**Comment by ghillert** [comment]
LGTM - merged with commit 1e41f6e8dce5da12e13af17f72ece28f7842e96a

**Pull request closed without merging**
