### PR TITLE
Refactor to use service classes for stream/task validation

### LINKED ISSUE #2441: Refactor AppValidationUtils to be a non static util class
Pass in required deps such as `DockerValidatorProperties` and `AppRegistryCommon`  The new class should have a method to return `DefinitionAppValidationStatus`

### PR DESCRIPTION
**Pull request by markpollack**
Fixes #2441

### CODE REVIEW

**Comment by jvalkeal** [comment]
@markpollack you had a stale branch as gunnar's 63d4ef728c6f8ea869ef6d3b9a2e8fa665d92de7 changed those conflicted files.

**Comment by jvalkeal** [comment]
LGTM. Fixing conflicts was slightly annoying but straightforward. I polished few places in tests to remove dead code and added some javadocs. Merging...

**Comment by jvalkeal** [comment]
Merged/squashed/polished per b934b4a583d0e6e6af6274c4d6770a658232ec47

**Comment by markpollack** [comment]
Sorry about the conflicts!

**Pull request closed without merging**
