### PR TITLE
Complete REST Documentation

### LINKED ISSUE #2538: Document all the fields returned by the RESTDocs
Investigate fieldWithPath to subsectionWithPath replacements.

Look where we want to doc all the fields vs. a subset ( batch responses can be quite lengthy)

The goal is to make sure we are pulling all the fields returned by the RESTDocs, so nothing is missed in the final doc artifacts.

### PR DESCRIPTION
**Pull request by oodamien**
Resolves #2538

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
LGTM.

**Comment by ilayaperumalg** [comment]
@oodamien I am not sure why this PR is marked as a draft version.

**Comment by ilayaperumalg** [comment]
LGTM

**Comment by sabbyanandan** [comment]
@oodamien: Why is this submtitted as "Draft"? Is this good to go?

**Comment by oodamien** [comment]
Done:
Task Definitions
Registered Applications
Stream Definitions

In Progress:
Audit Records

Todo:
Server Meta Information
Stream Deployments
Stream Validation
Task Executions
Task Scheduler
Task Validation
Job Executions
Job Instances
Job Step Executions
Runtime Information about Applications
Metrics for Stream Applications

**Comment by ilayaperumalg** [comment]
LGTM. @oodamien Great effort to get these changes in. 

Merging.

**Comment by ilayaperumalg** [comment]
Squashed, rebased and merged as c2736fc4

**Pull request closed without merging**
