### PR TITLE
Use 1.3 apps, expose port range of 9000-9010

### LINKED ISSUE #2356: HTTP source fails to deploy when stream containing it is deployed
I am running Spring Cloud Data Flow in version 1.6.0.RELEASE using the Docker Compose "approach" as described  in the Reference Guide with the plain vanilla Docker Compose file.

When I try to deploy the stream `http | log` from within the dashboard then `log` deploys fine but `http` fails and its STDOUT log says the following:

```
2018-08-07 18:26:54.326  INFO 162 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@28f67ac7: startup date [Tue Aug 07 18:26:54 GMT 2018];
 root of context hierarchy
2018-08-07 18:26:55.000  INFO 162 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAut
oConfiguration$$EnhancerBySpringCGLIB$$21bef148] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.3.RELEASE)

2018-08-07 18:26:55.323  INFO 162 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:8888
2018-08-07 18:26:55.435  INFO 162 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:8888. Will be trying the next url if available
2018-08-07 18:26:55.435  WARN 162 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/http-source/default": Connection refused (Connection r
efused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
2018-08-07 18:26:55.439  INFO 162 --- [           main] s.c.s.a.h.s.k.HttpSourceKafkaApplication : No active profile set, falling back to default profiles: default
2018-08-07 18:26:55.475  INFO 162 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@6adede5: startup date [Tue Aug 0
7 18:26:55 GMT 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@28f67ac7
2018-08-07 18:26:56.553  INFO 162 --- [           main] o.s.i.config.IntegrationRegistrar        : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be cre
ated.
2018-08-07 18:26:57.843  INFO 162 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=60f7b4ed-c0e2-31da-9379-6e49a356e6ef
2018-08-07 18:26:57.868  INFO 162 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2018-08-07 18:26:57.870  INFO 162 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
2018-08-07 18:26:58.312  INFO 162 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.kafka.annotation.KafkaBootstrapConfiguration' of type [org.springframework.kafka.annotation.KafkaBootstrapConfigu
ration$$EnhancerBySpringCGLIB$$d956ffce] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-08-07 18:26:58.428  INFO 162 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.Integratio
nManagementConfiguration$$EnhancerBySpringCGLIB$$7096a97a] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-08-07 18:26:58.445  INFO 162 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconf
igure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$21bef148] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-08-07 18:26:58.467  INFO 162 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.dsl.context.IntegrationFlowContext' of type [org.springframework.integration.dsl.context.IntegrationF
lowContext] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-08-07 18:26:58.912  INFO 162 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 45800 (http)
2018-08-07 18:26:58.975  INFO 162 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-08-07 18:26:58.976  INFO 162 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.31
2018-08-07 18:26:59.032  INFO 162 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.pa
th: [/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64/server:/usr/lib/jvm/java-1.8-openjdk/jre/lib/amd64:/usr/lib/jvm/java-1.8-openjdk/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2018-08-07 18:26:59.199  INFO 162 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-08-07 18:26:59.199  INFO 162 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3724 ms
2018-08-07 18:27:01.801  INFO 162 --- [ost-startStop-1] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService  'taskScheduler'
2018-08-07 18:27:02.540  INFO 162 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2018-08-07 18:27:02.593  INFO 162 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-08-07 18:27:02.593  INFO 162 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-08-07 18:27:02.594  INFO 162 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-08-07 18:27:02.594  INFO 162 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-08-07 18:27:02.594  INFO 162 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpTraceFilter' to: [/*]
2018-08-07 18:27:02.595  INFO 162 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webMvcMetricsFilter' to: [/*]
2018-08-07 18:27:03.016  WARN 162 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'org.springframework.cloud.stream.app.http.source.HttpSourceConfiguration$HttpSourceSecurityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.No
SuchBeanDefinitionException: No qualifying bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor<?>' available
2018-08-07 18:27:03.018  INFO 162 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2018-08-07 18:27:03.044  INFO 162 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-08-07 18:27:03.101  INFO 162 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-08-07 18:27:04.988 ERROR 162 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.security.config.annotation.ObjectPostProcessor' in your configuration.
```

### PR DESCRIPTION
**Pull request by chrisjs**
Resolves #2356

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Is there any reason why this is marked as `in-progress` ?

**Comment by ilayaperumalg** [comment]
LGTM

**Comment by chrisjs** [comment]
i think its because i tried creating my own waffle board and apparently that caused some random changing of labels.. that board is now deleted and ive removed the `in progress` label

**Comment by ilayaperumalg** [comment]
Rebased and merged as c33a131c

**Comment by chrisjs** [comment]
back ported to 1.6.x in 4b89a6

**Pull request closed without merging**
