### PR TITLE
Add support in shell to skip SSL validation

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes https://github.com/spring-cloud/spring-cloud-dataflow/issues/1081

### CODE REVIEW

**Comment by ghillert** [comment]
@ericbottard Needs documentation in the reference guide

**Comment by ericbottard** [comment]
I updated the usage.txt file.

When it comes to the reference docs, where would you see that new documentation (we don't really have a section pertaining to the shell)?

**Comment by ghillert** [comment]
We have a section in the reference guide under chapter `Using Self-Signed Certificates`. It already contains a few pointers in regards to the shell as well.

**Comment by ghillert** [comment]
LGTM - Merging. Will add reference documentation during merge.

**Comment by ghillert** [comment]
Merged with commits 032e453916c68a08de9821fef9d92b8f2cc8f982 and 59097274fc3500cdd9046e5a3c2b3ef4e17f417f

**Pull request closed without merging**
