### PR TITLE
Instructions for updating container with extra dependencies.

### PR DESCRIPTION
**Pull request by corneil**

### CODE REVIEW

**Comment by corneil** [comment]
@onobc, @markpollack  Can you take a look at this.

**Comment by onobc** [comment]
This seems like it should work @corneil . Did you test it on the Oracle driver? 

The previous advice (for stream-applications anyways) is to pull the repo locally and [rebuild w/ adjusted deps](https://docs.spring.io/stream-applications/docs/current/reference/html/#_patching_pre_built_applications). This is less intrusive, which is nice.

**Comment by corneil** [comment]
This obviously only addresses the k8s problem.
For CF we need to drop the executable from Spring Boot plugin so that dependencies can be added to application jars before publishing them in a private Maven Repo.

I believe that private Maven repo and private Container registry should be standard recommendations.

**Comment by klopfdreh** [comment]
Just a question for testing - is there any way to test .bat files with GitHub actions?

**Comment by corneil** [comment]
> Just a question for testing - is there any way to test .bat files with GitHub actions?

We will need to create a GitHub actions workflow targeting a Windows runner.

**Pull request merged**
