### PR TITLE
Harmonize shell commands to use id=type:name notation

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes https://github.com/spring-cloud/spring-cloud-dataflow/issues/438

### CODE REVIEW

**Comment by jvalkeal** [comment]
Shouldn't we change `register` as well as we now use:
```
dataflow:>app register --name foo --type sink --uri http://foo.com/foo
Successfully registered application 'sink:foo'

dataflow:>app unregister --name foo --type sink
Successfully unregistered application 'foo' with type sink
```

I find in confusing if we change only `unregister` command.

**Comment by ericbottard** [comment]
Not sure. I think it could be ok to add a `--id <type>:<name>` as an _alternative_. To me, the first driver for id in the unregister case, is so that we can easily autocomplete an existing id (because Spring Shell has no way of completing `--name` on its own, even if `--type` would have been set earlier). This does not apply to the register case (we could autocomplete the first part of `--id` though).

**Comment by markpollack** [comment]
Well despite the fact that it might help with autocomplete to use the id format for unregister since we can provide that guidance, it makes for a real asymmetry between register and unregister, which should be the most similar vs. the info command.  I'd actually suggest just leaving it as it is.  I thought the original motivation for this issue was that in some places we had used `type:name` and others `name:type`.

**Comment by ericbottard** [comment]
> I thought the original motivation for this issue was that in some places we had used type:name and others name:type.

We kind of have, as the current implementation uses `--name` in a lax way and accepts `<name>:<type>` in it. So at the minimum we should get rid of that behavior IMHO

**Comment by markpollack** [comment]
that sound good to me.   I don't think there are any folks clamoring for an overload `id` option for reg/unreg that takes type:name - right?

**Comment by ericbottard** [comment]
@markpollack Changed the PR to reflect latest discussion. Now `--name` is just a (mandatory) name

**Comment by markpollack** [comment]
merged as 3fba890fc8405d9fb0dfecec6b0b885ae3935d46

**Pull request closed without merging**
