### PR TITLE
Support commandLineArgs for specific apps in workflow

### LINKED ISSUE #3919: Add support to override "composed-task-arguments" for a particular child in the graph
As a user, with multiple child tasks in the graph, when using the `composed-task-arguments` property, the override is passed to all the children. I'd like to pass only to a particular child instead. Specifically, if I want to launch "same" task a few times, but the only one of many launches should receive the override, this enhancement is required then.

Definition:
```
task create foo --definition “tb1: timestamp-batch && tb2: timestamp-batch && t1: timestamp”
```

Today:
```
task launch  --arguments “--composedTaskArguments=--timestamp.format=YYYYMMDD”
```

This passes `--timestamp.format=YYYYMMD` to all the 3 children in the graph (i.e., `tb1`, `tb2`, and `t1`).

If I have to override _only_ for `tb2`, it might be nice to have an option to pass it as:
```
task launch  --arguments “--composedTaskArguments=--tb2.timestamp.format=YYYYMMDD”
```

Maybe even a different top-level property in CTR could be useful to solution it.

Migrated from https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/92

### LINKED ISSUE #3921: DeploymentPropertyUtils.parseArgumentList does not support = embedded in quotes
Hence `--composedTaskArguments="--1.timestamp.format=YYYY --timestamp.timestamp.format=MM --foo=bar bar=\"bazzz buzz\""`
 is being parsed as 
```
--composedTaskArguments="--1.timestamp.format=YYYY
--timestamp.timestamp.format=MM 
--foo=bar 
bar=\"bazzz buzz\""
```
Instead of a full string

### PR DESCRIPTION
**Pull request by cppwfs**
resolves #3919  
resolves #3921

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@cppwfs Given this PR addresses both the CTR feature as well as a bug, I have the following suggestion.

We need to have the CTR feature merged into `master` as an enhancement to CTR in 2.6.x while the fix for deployment properties parsing the `arguments` needs to backported into 2.5.x for our 2.5.1.RELEASE.

Hence, could you submit a separate PR for 2.5.x for #3921 so that we can merge only that change into 2.5.1.RELEASE?

**Comment by sabbyanandan** [comment]
We only wanted this in 2.6.x line anyway; is there any compelling reason to backport it to 2.5.x?

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Copied the changes that fixed #3921 explicitly and applied them into 2.5.x as d7a17d338

**Comment by ilayaperumalg** [comment]
All the changes from this PR are merged into master as 51a0c7936ebac862c56cbe7365e876e4bcad9ed0

**Pull request merged**
