### PR TITLE
Assert invalid URLResource path

### LINKED ISSUE #1788: Assert invalid URLResource path
We need to throw exception when an invalid URL Resource path (ie., the path that doesn't conform to <resource>-<version>.jar) is provided for the resource URI.

### LINKED ISSUE #1789: Stream fails to deploy with invalid HTTP URI via Skipper
As a user, when deploying stream with invalid URI (via Skipper), I see the `StringIndexOutOfBoundsException`. Specifically, I'm also using Ilaya's [SCDF PR](https://github.com/spring-cloud/spring-cloud-dataflow/pull/1787/files) and [Skipper PR](https://github.com/spring-cloud/spring-cloud-skipper/pull/313/files) that includes the validation to prevent this from happening.

action:
```
dataflow:>app register --name dd --type processor --uri http://com.com-0.0.2-SNAPSHOT
Successfully registered application 'processor:dd'
dataflow:>
dataflow:>stream create fooz --definition "http | dd | log"
Created new stream 'fooz'
dataflow:>stream skipper deploy --name fooz --platformName default
```

error:
```
2017-11-16 13:51:21.628 ERROR 65725 --- [nio-9393-exec-6] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[na:1.8.0_121]
```

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- If the URL resource has the version in its path, then throw exception to avoid conflict when doing upgrade of the URLResource with just version change
 - Add tests

Resolves #1788
Resolves #1789

### CODE REVIEW

**Comment by sabbyanandan** [comment]
Continuing the conversation from #1789, with the recent commit, I now get:

```
2017-11-16 19:49:23.424 ERROR 89561 --- [nio-9393-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

java.lang.IllegalArgumentException: URI path doesn't exist
```

Shell shows:

```
2017-11-16 19:49:23.424 ERROR 89561 --- [nio-9393-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

java.lang.IllegalArgumentException: URI path doesn't exist
```

This is much better!

Aside though, I still see:

```
Downloading [https://github.com/sabbyanandan/sandbox/raw/master/jars/fooTran-0.0.1-SNAPSHOT.jar] to /var/folders/c3/ctx7_rns6x30tq7rb76wzqwr0000gs/T/spring-cloud-deployer5856885378506488305/3af175e7ff48ef977bde83b783dd9cedb76a6692
```

and

```
Downloading [https://github.com/sabbyanandan/sandbox/raw/master/jars/fooTran-0.0.1-SNAPSHOT.jar] to /var/folders/c3/ctx7_rns6x30tq7rb76wzqwr0000gs/T/spring-cloud-deployer5856885378506488305/3af175e7ff48ef977bde83b783dd9cedb76a6692
```

We are still downloading and 2x, why? Can we prevent that?

**Comment by ilayaperumalg** [comment]
@sabbyanandan Unfortunately, that is how it works now when we do the deployment from SCDF -> Skipper and we planned to address this in the next release.

The reason it downloads at the SCDF is that because of the way LRUCleaningResourceLoader works. It always downloads the `UrlResource` when `getResource` is invoked. Created https://github.com/spring-cloud/spring-cloud-deployer/issues/244 to track this.

**Comment by ilayaperumalg** [comment]
We could, in fact, remove the use of `LRUCleaningLoader` in Skipper and use the `DelegatingResourceLoader` directly at the expense of having to clean up the downloaded file explicitly.

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
Squashed / Mergd

**Pull request closed without merging**
