### PR TITLE
Fix book configuration

### LINKED ISSUE #1398: Docs are missing icons for Note etc
Last change to `index.adoc` seems to have caused the icons for Notes etc to be lost

### PR DESCRIPTION
**Pull request by trisberg**
Resolves #1398

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@trisberg I am trying to understand how to check/reproduce this issue. I built docs locally (from the latest master) and the contents look good.

**Comment by trisberg** [comment]
Take a look at http://docs.spring.io/spring-cloud-dataflow/docs/1.2.0.BUILD-SNAPSHOT/reference/htmlsingle/#dataflow-documentation-getting-help

The icon for the note is missing

**Comment by ilayaperumalg** [comment]
LGTM, verified the doc as well.

**Comment by ilayaperumalg** [comment]
Rebased and merged as 41eed4a22ddcd990325bb595383ff99e4a0bccd3

**Pull request closed without merging**
