### PR TITLE
gh-870 Provide DataflowTemplate Constructor without the RestTemplate

### PR DESCRIPTION
**Pull request by ghillert**
Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/870

### CODE REVIEW

**Comment by ericbottard** [comment]
I think it would be better to accept any RestTemplate, and apply the mixins that we want.
This would take care of https://github.com/spring-cloud/spring-cloud-dataflow/issues/871 as well

**Comment by ghillert** [comment]
@ericbottard Made some changes - If a RestTemplate is provided, the MixIns will be applied now. Also provide substantially more JavaDoc documentation and also provide JUnit Tests for the DataFlowTemplate. I hope this satisfies most use-cases.

**Comment by ericbottard** [comment]
Getting test errors on `testDataFlowTemplateContructorWithNonExistingUri` (different error message than expected, unknown host vs timeout). I will remove that part of the test and merge.

**Comment by ericbottard** [comment]
Merged with a couple of small changes as 762878e

**Pull request closed without merging**
