### PR TITLE
Docker Resource with host name isn't recognized

### LINKED ISSUE #2107: Docker Resource with IP address isn't recognized
192.168.99.100:80/myrepo/rabbitsink:current will fail.

```      @Test
      public void testDockerResourceProcessingSO() {
              DockerResource dockerResource = new DockerResource("192.168.99.100:80/myrepo/rabbitsink:current");
              assertThat(ResourceUtils.getResourceWithoutVersion(dockerResource)).isEqualTo("docker:192.168.99.100:80/myrepo/rabbitsink");
              assertThat(ResourceUtils.getResourceVersion(dockerResource)).isEqualTo("current");
      }
```
fails

### PR DESCRIPTION
**Pull request by markpollack**
- Use DockerImage utility class to parse parts of docker resource
- Add quick hack wrt to return character failing test on windows
- Had to reformat some test files as checkstyle was failing

Fixes #2107

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
LGTM

**Comment by jvalkeal** [comment]
As is lgtm

**Comment by ilayaperumalg** [comment]
Merging.

**Comment by ilayaperumalg** [comment]
Rebased and merged as e2e8ebe9

**Pull request merged**
