### PR TITLE
Lower the case of constraint foreign key

### PR DESCRIPTION
**Pull request by herman-d**
Context:
An error with error code [1769]; Foreign key 'TASK_METADATA_FK' references invalid column 'TASK_EXECUTION_ID' in referencing table 'task_execution_metadata'. was thrown when flyway executing migration script for SQL Server with Case Sensitive collation.

It was due to the script use upper case 'TASK_EXECUTION_ID' key referenced to a field in the task_execution_metadata table which is created in lower case 'task_execution_id'

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@herman-d Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4206)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4206) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@herman-d Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4206)!

**Comment by jvalkeal** [comment]
Flyway is actually using https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/db/migration/sqlserver/V2__Add_Descriptions_And_OriginalDefinition.java

What is your sqlserver version and OS as we run some tests on MS's ubuntu version where all these has been fine and haven't seen any reports until now.

**Comment by jvalkeal** [comment]
I assume sqlserver were installed to be case sensitive as it's insensitive on default. Also to be on a safe side, It should get changed for other db's as well.

**Comment by jvalkeal** [comment]
Created an issue for this so that it's easier to find in a future. Looks like we should also modify postgresql/mysql scripts, but that's something I can "polish" during a merge.

**Comment by jvalkeal** [comment]
Merged per 3b5c221eb9a088c9fc70680fcc5c33d380d219d5

**Pull request closed without merging**
