### PR TITLE
Previously flaky test notCreateLongLivedThreadsAfterExecution is passing

### PR DESCRIPTION
**Pull request by corneil**
Removed `@Disabled`

### CODE REVIEW

**Review by cppwfs — CHANGES_REQUESTED** [review]
I ran it 10 times and it failed once.  Still appears to be flakey.

**Comment by corneil** [comment]
I modified the test to count live threads.

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
Rebased, Squashed, Merged.  Thanks @corneil !!!

**Pull request closed without merging**
