### PR TITLE
Fix link to local deployer (DEBUG logs)

### PR DESCRIPTION
**Pull request by garyrussell**
Inadvertently fixed a bunch of trailing spaces too.

### CODE REVIEW

**Comment by garyrussell** [comment]
Sorry; atom strips trailing white spaces by default.

Line 101.

Hint - you can get github to ignore white-space only changes by adding `?w=1` to the url...

https://github.com/spring-cloud/spring-cloud-dataflow/pull/1249/files?w=1

**Comment by garyrussell** [comment]
@trisberg ^^

**Comment by trisberg** [comment]
@garyrussell nice, thanks for the tip, LGTM, will merge

**Comment by garyrussell** [comment]
More secrets here: [GitHub Secrets](https://github.com/blog/967-github-secrets).

**Pull request merged**
