### PR TITLE
Avoid back and forth conversion of deployment properties

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes https://github.com/spring-cloud/spring-cloud-dataflow/issues/1228

### CODE REVIEW

**Comment by jvalkeal** [comment]
Looks good other that we need to fix UI as well. UI simply sends
```
Request URL:http://localhost:9393/streams/deployments/foostream?properties=deployer.*.count%3D2
```
and that not gets lost. Should we wait merging this PR until we have fix for UI?

**Comment by jvalkeal** [comment]
I was writing new issue for `spring-cloud-dataflow-ui` and realised that it only have one field for passing in deployment properties and cannot send those using a map as UI cannot do parsing.

**Comment by ericbottard** [comment]
Would be good to find some sort of solution before RC though, IMO.
Maybe we can keep a deprecated, content-negotiated endpoint that accepts a raw unparsed string for the UI.

**Comment by jvalkeal** [comment]
Yeah, I don't see any other option if UI allows to define comma-delimited property string. Thought it might be good if in UI we'd force to use separate text boxes for each property.

**Comment by sabbyanandan** [comment]
UI updates will be supported via: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/180.

**Comment by ghillert** [comment]
Also linking to https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/181

See my comment regarding YAML support. I have the feeling we should also support raw YAML to be passed in for deployment properties.

Furthermore, a super-minor note: when passing key/value pairs via REST controllers, should we standardize on what method parameter type to use? E.g. in [sdfsdf](https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/181) we use `java.util.Properties` when passing key-value pairs.

**Comment by ghillert** [comment]
@ericbottard Besides my comment regarding `Map<String, String> properties` versus `Properties properties`, I think this should be ok. The change for the UI is literally just 1 line and will be done once this is merged.

**Comment by jvalkeal** [comment]
merged per https://github.com/spring-cloud/spring-cloud-dataflow/commit/0d30bf26da3559ea14d3567ef70fb2997b3a6ed5

**Pull request closed without merging**
