### PR TITLE
Implement scaling at runtime

### PR DESCRIPTION
**Pull request by Mwea**
TODO improve the mechanics to update value in the spring cloud dataflow dashboard

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Mwea Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=1041)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=1041) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Mwea Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=1041)!

**Comment by sabbyanandan** [comment]
@Mwea: Thanks for the contribution! As shared in this [update](https://github.com/spring-cloud/spring-cloud-dataflow/issues/1034#issuecomment-262266286), we will design pair on the overall approach next week. We will certainly review your contribution in that context and get back to you with an update. 

Thanks for your patience. 😄

**Comment by Mwea** [comment]
Hi there ! Any news about this update? I'm curious to see your approach of this feature

**Pull request closed without merging**
