### PR TITLE
gh-2168 Use JpaTransactionManager

### PR DESCRIPTION
**Pull request by ghillert**
- Fixes an issue were with a small connection pool size, methods hang or time out (Connection pool exhaustion) due to JPA calls occurring outside TX
- Also fixes an unclosed DB connection issue occurring in the `DataflowRdbmsInitializer`

Resolves spring-cloud/spring-cloud-dataflow#2168
Resolves spring-cloud/spring-cloud-dataflow#2169

### CODE REVIEW

**Comment by jvalkeal** [comment]
This is probably one of those commits where we should have a proper commit message to know why this change is done, what it fixes and why it fixes it.

**Comment by markpollack** [comment]
Too many connections are being used, the `list` and `info` controller methods invoke JPA based repositories.   Part of this is because bad layering wrt service/controller layer.  In another branch I fixed some, but not all of the layering problems and there are additional connections being used to create the jpa query.

```[http-nio-9393-exec-9] --- getConnection(23edefbe):  > JdkDynamicAopProxy.invoke(213) > $Proxy148.findOne(-1) > StreamDefinitionController.display(273)
[http-nio-9393-exec-9] --- retConnection(23edefbe):  > JdkDynamicAopProxy.invoke(213) > $Proxy148.findOne(-1) > StreamDefinitionController.display(273)
[http-nio-9393-exec-9] --- getConnection(27d27f1b):  > JdkDynamicAopProxy.invoke(213) > $Proxy148.state(-1) > StreamDefinitionController$Assembler.<init>(303) > StreamDefinitionController.display(277)
[http-nio-9393-exec-9] --- retConnection(27d27f1b):  > JdkDynamicAopProxy.invoke(213) > $Proxy148.state(-1) > StreamDefinitionController$Assembler.<init>(303) > StreamDefinitionController.display(277)
[http-nio-9393-exec-1] --- getConnection(6493ad43):  > JdkDynamicAopProxy.invoke(213) > $Proxy148.platformList(-1) > SkipperStreamDeploymentController.platformList(102)
[http-nio-9393-exec-10] --- getConnection(5c7b702):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findAllByTypeAndNameIsLike(-1) > SkipperAppRegistryController.list(139)
[http-nio-9393-exec-10] --- getConnection(7f5bcae1):  > $Proxy126.joinTransaction(-1) > $Proxy126.createQuery(-1)
[http-nio-9393-exec-1] --- retConnection(6493ad43):  > JdkDynamicAopProxy.invoke(213) > $Proxy148.platformList(-1) > SkipperStreamDeploymentController.platformList(102)
[http-nio-9393-exec-10] --- retConnection(5c7b702):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findAllByTypeAndNameIsLike(-1) > SkipperAppRegistryController.list(139)
[http-nio-9393-exec-3] --- getConnection(365f69a2):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findAllByTypeAndNameIsLike(-1) > SkipperAppRegistryController.list(139)
[http-nio-9393-exec-3] --- getConnection(267dda22):  > $Proxy126.joinTransaction(-1) > $Proxy126.createQuery(-1)
[http-nio-9393-exec-10] --- retConnection(7f5bcae1):  > $Proxy126.close(-1)
[http-nio-9393-exec-3] --- retConnection(365f69a2):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findAllByTypeAndNameIsLike(-1) > SkipperAppRegistryController.list(139)
[http-nio-9393-exec-2] --- getConnection(5431c70f):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findAllByTypeAndNameIsLike(-1) > SkipperAppRegistryController.list(139)
[http-nio-9393-exec-2] --- getConnection(38a91144):  > $Proxy126.joinTransaction(-1) > $Proxy126.createQuery(-1)
[http-nio-9393-exec-3] --- retConnection(267dda22):  > $Proxy126.close(-1)
[http-nio-9393-exec-2] --- retConnection(5431c70f):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findAllByTypeAndNameIsLike(-1) > SkipperAppRegistryController.list(139)
[http-nio-9393-exec-2] --- retConnection(38a91144):  > $Proxy126.close(-1)
[http-nio-9393-exec-4] --- getConnection(12586b6c):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findDefault(-1) > SkipperAppRegistryController.info(180)
[http-nio-9393-exec-4] --- getConnection(46850fa6):  > $Proxy126.joinTransaction(-1) > $Proxy126.createQuery(-1)
[http-nio-9393-exec-4] --- retConnection(12586b6c):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findDefault(-1) > SkipperAppRegistryController.info(180)
[http-nio-9393-exec-4] --- getConnection(73b1a8d0):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.getAppMetadataResource(-1) > SkipperAppRegistryController.getDetailedAppRegistrationResource(168) > SkipperAppRegistryController.info(181)
[http-nio-9393-exec-4] --- retConnection(73b1a8d0):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.getAppMetadataResource(-1) > SkipperAppRegistryController.getDetailedAppRegistrationResource(168) > SkipperAppRegistryController.info(181)
[http-nio-9393-exec-7] --- getConnection(30cddc53):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findDefault(-1) > SkipperAppRegistryController.info(180)
[http-nio-9393-exec-7] --- getConnection(137ce5d):  > $Proxy126.joinTransaction(-1) > $Proxy126.createQuery(-1)
[http-nio-9393-exec-4] --- retConnection(46850fa6):  > $Proxy126.close(-1)
[http-nio-9393-exec-7] --- retConnection(30cddc53):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findDefault(-1) > SkipperAppRegistryController.info(180)
[http-nio-9393-exec-7] --- getConnection(21830d94):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.getAppMetadataResource(-1) > SkipperAppRegistryController.getDetailedAppRegistrationResource(168) > SkipperAppRegistryController.info(181)
[http-nio-9393-exec-7] --- retConnection(21830d94):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.getAppMetadataResource(-1) > SkipperAppRegistryController.getDetailedAppRegistrationResource(168) > SkipperAppRegistryController.info(181)
[http-nio-9393-exec-5] --- getConnection(3eb68bfb):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findDefault(-1) > SkipperAppRegistryController.info(180)
[http-nio-9393-exec-7] --- retConnection(137ce5d):  > $Proxy126.close(-1)
[http-nio-9393-exec-5] --- getConnection(789d60ef):  > $Proxy126.joinTransaction(-1) > $Proxy126.createQuery(-1)
[http-nio-9393-exec-5] --- retConnection(3eb68bfb):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.findDefault(-1) > SkipperAppRegistryController.info(180)
[http-nio-9393-exec-5] --- getConnection(494a80e8):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.getAppMetadataResource(-1) > SkipperAppRegistryController.getDetailedAppRegistrationResource(168) > SkipperAppRegistryController.info(181)
[http-nio-9393-exec-5] --- retConnection(494a80e8):  > JdkDynamicAopProxy.invoke(213) > $Proxy129.getAppMetadataResource(-1) > SkipperAppRegistryController.getDetailedAppRegistrationResource(168) > SkipperAppRegistryController.info(181)
[http-nio-9393-exec-5] --- retConnection(789d60ef):  > $Proxy126.close(-1)```

**Comment by ghillert** [comment]
@jvalkeal @markpollack Added a better commit message

**Comment by markpollack** [comment]
Added `@Transactional` to Stream services as otherwise would get lockup creating a stream with only 1 connection in the connection pool.  Tested using 

```
java -jar spring-cloud-dataflow-server-local/target/spring-cloud-dataflow-server-local-1.5.0.BUILD-SNAPSHOT.jar --spring.cloud.dataflow.features.skipper-enabled=true --spring.datasource.tomcat.max-active=1
```
Tests using the connection logging aspect showed expected behavior.

Merged as `ef31de324ee20322199bf32ef482b5ae6af7e892`

**Pull request closed without merging**
