### PR TITLE
Set SCDF to use Milestone vs snapshot.

### PR DESCRIPTION
**Pull request by cppwfs**
SCDF should be using M1 milestone and not snapshot.

### CODE REVIEW

**Comment by markpollack** [comment]
Why not snapshot?

**Comment by markpollack** [comment]
Because of https://github.com/spring-cloud/spring-cloud-dataflow/issues/390

**Comment by cppwfs** [comment]
Correct

**Comment by markfisher** [comment]
I don't think this is necessary. The latest snapshot dependency will always include the latest commits, even if those were in a milestone. The actual problem is that the `TaskDatabaseInitializer` has been replaced, and yet it is still being included within the dataflow configuration.

**Comment by markfisher** [comment]
Closing since instead of this PR, we need the one that addresses #391

**Comment by markfisher** [comment]
reopening so that we keep spring-cloud-dataflow on M1 of spring-cloud-task

**Comment by markfisher** [comment]
By keeping spring-cloud-dataflow on the M1 of spring-cloud-task we will not be bringing in the changes to  the initializer. Then, after the next dataflow milestone, we will move back to snapshots at which point #391 will be necessary.

**Comment by markfisher** [comment]
merged

**Pull request merged**
