### PR TITLE
Log file comes back as a JSON encoded String value

### PR DESCRIPTION
**Pull request by mikebski**
- so parse that to make it display correctly in the console. 

Fixes 3723

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mikebski Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=3724)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=3724) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mikebski Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=3724)!

**Comment by ilayaperumalg** [comment]
@mikebski LGTM, merging.

**Comment by ilayaperumalg** [comment]
@mikebski Thank you for the contribution! 

Rebased, fixed the copyright year, adjusted the commit description and merged as 151f7ad7242dc17b6278ee0352472a950a047313

**Pull request closed without merging**
