### PR TITLE
Support deploying docker apps in local data flow server

### LINKED ISSUE #695: Could not deploy docker app resources
When using app resource URI as docker URL, the stream deployment fails as it could not load the docker resource file.

To reproduce:

> dataflow:>app register --type source --name time --uri docker:springcloudstream/time-source-kafka:latest
> dataflow:>app register --type sink --name log --uri docker:springcloudstream/log-sink-kafka:latest
> dataflow:>stream create a1 --definition "time | log" --deploy

Following exception is thrown:

```
java.lang.RuntimeException: Exception trying to list configuration properties for application ServletContext resource [/docker:springcloudstream/log-sink-kafka:latest]
    at org.springframework.cloud.dataflow.configuration.metadata.ApplicationConfigurationMetadataResolver.listProperties(ApplicationConfigurationMetadataResolver.java:123) ~[spring-cloud-dataflow-configuration-metadata-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.qualifyParameters(StreamDeploymentController.java:267) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deployStream(StreamDeploymentController.java:243) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deploy(StreamDeploymentController.java:186) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_20]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_20]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_20]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_20]
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RE
...
...
Caused by: java.lang.IllegalArgumentException: File must exist
    at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:67) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:51) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:95) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:65) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61) ~[spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
    at org.springframework.cloud.dataflow.configuration.metadata.ApplicationConfigurationMetadataResolver.listProperties(ApplicationConfigurationMetadataResolver.java:87) ~[spring-cloud-dataflow-configuration-metadata-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Add docker resource loader into DelegatingResourceLoader bean for `local` data flow server configuration

This resolves #695

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Here are the steps to run:

```
dataflow:>app import --uri http://bit.ly/1-0-4-GA-stream-applications-rabbit-docker
dataflow:>stream create a1 --definition "time | log"
```

In this case, I am running `rabbitmq` inside docker machine and use it as the broker between `time` and `log` apps.

Get the IP address of the RabbitMQ:

```
> docker ps
> docker inspect <container-id-of-rabbitmq>
```

then, use the IP address as `spring.rabbitmq.host` in the deployment property:

```
dataflow:>stream deploy a1 --properties "app.*.DOCKER_TLS_VERIFY=1,app.*.DOCKER_HOST=tcp://192.168.99.100:2376,app.*.DOCKER_CERT_PATH=/home/.docker/machine/machines/default,app.*.DOCKER_MACHINE_NAME=default,app.time.server.port=9191,app.log.server.port=9292,app.*.spring.rabbitmq.host=my-rabbit"
```

Once merged, will update the documentation for the same.

**Comment by ericbottard** [comment]
Haven't looked at the code yet, but I still don't understand why the user would pass `server.port`.
The deployer should compute a random port, and use that as the NATed host port. Inside the container(s), all apps should use 8080. resulting in the deployer issuing this bit of command : `-p <randomPort>:8080`

Also, we should have a look at docker networks and the best practices for "linking" apps together in the new docker ecosystem.

**Comment by ilayaperumalg** [comment]
> Inside the container(s), all apps should use 8080. resulting in the deployer issuing this bit of command : -p <randomPort>:8080

Please look at the code ;) The current changes exactly does that. I thought explicit port is needed only when the apps like `http`. Given this is only for `local` deployer, I believe we don't have to deal with `linking` the apps by inspecting the docker `network` as all the required properties can be passed via deployment properties as mentioned above.

**Comment by ericbottard** [comment]
Will do :)

But then why does your example (still?) use this:
```
dataflow:>stream deploy a1 --properties "app.*.DOCKER_TLS_VERIFY=1,app.*.DOCKER_HOST=tcp://192.168.99.100:2376,app.*.DOCKER_CERT_PATH=/home/.docker/machine/machines/default,app.*.DOCKER_MACHINE_NAME=default,
app.time.server.port=9191,  <-- 
app.log.server.port=9292,  <-- 
app.*.spring.rabbitmq.host=my-rabbit"
```

(maybe this is just from a previous comment).

As far as linking is concerned, I think it would be nice to be able to say something like

```
stream deploy ticktock --properties "app.*.linked-containers=rabbit"
```

and have every app "see" the rabbit container (hence, if using default ports, everything would just work™)
WDYT?

**Comment by ericbottard** [comment]
LGTM, tested with the new "docker" for mac, which simplifies configuration to just specifying the IP address of rabbit.

Confirmed that graceful shutdown works correctly as well

**Comment by ilayaperumalg** [comment]
> But then why does your example (still?) use this:

That is just one of the properties (server.port) I chose (unfortunately) :-)

for the app `linking`: yes, that would be nice to have. But, my question is do we really need those for `local` deployer given the other way of specifying the properties.

**Comment by Mwea** [comment]
Does this PR could be the opportunity of developping a spring cloud deployer for docker swarm ? 
Using this library could be usefull by the way
https://github.com/spotify/docker-client

**Pull request merged**
