### PR TITLE
Move to spring-cloud-dataflow-build

### PR DESCRIPTION
**Pull request by jvalkeal**
- Simple change to use spring-cloud-dataflow-build instead
  of spring-cloud-build.
- Relates spring-cloud/spring-cloud-dataflow#3670

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@jvalkeal Are we planning to do the other possible refactoring in the POM files based on the `spring-cloud-dataflow-build` changes in a separate PR?

**Comment by jvalkeal** [comment]
Not really sure what you mean but if you mean polishing poms and removing unneeded stuff if favour of spring-cloud-dataflow-build, then yes those needs to happen but probably not within these first PR's.

**Comment by ilayaperumalg** [comment]
> if you mean polishing poms and removing unneeded stuff if favour of spring-cloud-dataflow-build, then yes those needs to happen but probably not within these first PR's.

That's exactly what I meant :-) and sure, let's take care of the changes in separate PRs.

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Merged as 7c7e10824dbf71fa436e84ec163c586e084d867c

**Pull request closed without merging**
