### PR TITLE
gh-819 Enable Sonar Builds + JaCoCo Code Coverage

### PR DESCRIPTION
**Pull request by ghillert**
Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/819

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Are there any steps to configure/view the code coverage results?

**Comment by ilayaperumalg** [comment]
@ghillert Could you provide some detail on this?

**Comment by ghillert** [comment]
Sorry for the delay:

* Download SonarQube 6.0 - http://www.sonarqube.org/downloads/
* Ensure you start it with JDK8 in `sonarqube-6.0/bin/macosx-universal-64/sonar.sh`
* For console output execute as: `./sonar.sh console`
* You can access the dashboard at `http://localhost:9000/`
* On my system I ran into an issue with Ruby ... had to execute `rvm use system`
* Now go to SCDF base directory and execute `mvn clean package sonar:sonar`
* The build should run successfully and a new report should be available on the Sonar Dashboard

**Comment by ghillert** [comment]
Rebased the code.

**Comment by ilayaperumalg** [comment]
Thanks @ghillert. LGTM, merging.

**Pull request merged**
