### PR TITLE
Fixes gh-4297 (#4297)

### LINKED ISSUE #4297: the endpoint tasks/definitions returns not masked credentials
**Description:**
the end-point: tasks/definitions/{name}?manifest=true return credentials (passwords, keys, tokens) as is, but they should be masked. The issue only related with "arguments" json part.

**Release versions:**
{
  "versions": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.7.0"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.7.0"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.0.0"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.7.0",
      "url": "https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.7.0/spring-cloud-dataflow-shell-2.7.0.jar"
    }
  },
  "features": {
    "streams": true,
    "tasks": true,
    "schedules": true,
    "monitoringDashboardType": "GRAFANA"
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": "2.6.0",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.6.0",
      "javaVersion": "11.0.8",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformSpecificInfo": {
        "default": "kubernetes"
      },
      "platformType": "Skipper Managed",
      "springBootVersion": "2.3.5.RELEASE",
      "springVersion": "5.2.10.RELEASE"
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "2.5.0",
        "deployerName": "KubernetesTaskLauncher",
        "deployerSpiVersion": "2.5.0",
        "javaVersion": "11.0.8",
        "platformApiVersion": "v1",
        "platformClientVersion": "unknown",
        "platformHostVersion": "unknown",
        "platformSpecificInfo": {
          "namespace": "default",
          "master-url": "https://10.96.0.1:443/"
        },
        "platformType": "Kubernetes",
        "springBootVersion": "2.3.5.RELEASE",
        "springVersion": "5.2.10.RELEASE"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "https://grafana:3000",
    "source": "default-scdf-source",
    "refreshInterval": 15
  },
  "security": {
    "isAuthentication": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  }
}

**Custom apps:**
<none>

**Steps to reproduce:**
- follow by instructions as described here: https://dataflow.spring.io/docs/installation/kubernetes/kubectl/
- k8s should have entryPointStyle = exec
- spring.cloud.dataflow.task.use-kubernetes-secrets-for-db-credentials=false
- install standard batch application (timestamp, etc)
- create task: task create --name task1 --definition "timestamp"
- launch task: task launch --name task1
- goto http://localhost:9393/dashboard/#/tasks-jobs/tasks/task1 

**Screenshots:**
50677498-9080-44BE-BD98-AA6803279DB1

**Additional context:**
<none>

### PR DESCRIPTION
**Pull request by ebezdomnikov**
Resolves #4297.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ebezdomnikov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4298)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4298) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ebezdomnikov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4298)!

**Comment by sabbyanandan** [comment]
Nicely done, @ebezdomnikov. Glad you were able to figure things out and submit the fix. 👏

**Comment by jvalkeal** [comment]
@ebezdomnikov Could you rebase this PR as build issue(due to changes to cloud 2020.0.0) should not be fixed in master.

**Comment by ebezdomnikov** [comment]
> @ebezdomnikov Could you rebase this PR as build issue(due to changes to cloud 2020.0.0) should now be fixed in master.

Hey @jvalkeal, I hope you're doing good. I've made the rebase. Please let me know if something else should be adjusted.

Thank you!

**Comment by jvalkeal** [comment]
Sorry for delay handling this. I think pr looks good!

**Pull request merged**
