### PR TITLE
Add security to schedule restful endpoints

### LINKED ISSUE #2404: Update dataflow-server-defaults.yml to include /tasks/schedules
Looks like `dataflow-server-defaults.yml` needs to be updated with the following:

```
            # Task Schedules

            - GET    /tasks/schedules                => hasRole('ROLE_VIEW')
            - GET    /tasks/schedules/*              => hasRole('ROLE_VIEW')
            - POST   /tasks/schedules                => hasRole('ROLE_CREATE')
            - DELETE /tasks/schedules/*              => hasRole('ROLE_CREATE')
```

and any corresponding tests. Otherwise when logged into the dashboard, a 403 error occurs when clicking on the schedules tab

### PR DESCRIPTION
**Pull request by cppwfs**
resolves #2404

Tested against SCDF-CF-Server

### CODE REVIEW

**Comment by chrisjs** [comment]
two things:

* in `configuration.adoc` we have a section of `Customizing Authentication` that indicates `The default rules are as follows:` - for consistency, seems that section should be updated as well with these paths

* i see there are tests in the local server security package for example `LocalServerSecurityRootWithUsersFileTestsWithTasksAndWithoutStreamsMetricsAndSchedules` - might it be worth doing the same but to assert on schedule path auth? i didn't see it covered elsewhere

**Comment by cppwfs** [comment]
updated the configuration.adoc as requested.  Also created story #2417 to add tests for Scheduler Security endpoints when a LocalScheduler IMPL is available.

**Comment by chrisjs** [comment]
merged in 45372e9

**Comment by chrisjs** [comment]
this has also been back ported to 1.6.x per the issue description and label added here

**Pull request closed without merging**
