### PR TITLE
renaming modules to apps

### PR DESCRIPTION
**Pull request by markfisher**
Resolves spring-cloud/spring-cloud-dataflow#535

### CODE REVIEW

**Comment by trisberg** [comment]
There are still a lot of classnames with "Module" in them like:

ModuleDefinition
ModuleDeploymentId
ModuleJarLauncher
etc.

Should they be renamed too?

**Comment by markfisher** [comment]
eventually we should, but maybe as a follow-up - the `ModuleDefinition

**Comment by trisberg** [comment]
what about `http://localhost:9393/runtime/modules`

**Comment by markfisher** [comment]
I think we should address the `/runtime/modules` one within the scope of this PR. Looking at it now.

**Comment by markfisher** [comment]
working on some changes for `ModuleDefinition` etc... will update with at least one more commit

**Comment by trisberg** [comment]
I won't have time to look at this today or tomorrow Tuesday (I'm traveling) so if someone else ( @ilayaperumalg ) wants to have a go, go for it. I can pick it back up Wednesday this week.

**Comment by trisberg** [comment]
tried to rebase and merge, but there were a bunch of conflicts and code didn't compile after rebase - maybe some new code that also needs the renaming

**Comment by trisberg** [comment]
Rebased, squashed and merged as commit ea14d83c267356978e9b73f8387185fd999b6cc2

**Comment by trisberg** [comment]
Fixed newly added code in commit e03a2db23d67190ff95d2702e1dc911e18761c4e

**Comment by markfisher** [comment]
Thanks @trisberg! Were you by chance working off this PR *prior* to my addition of that last commit? (where I had rebased): https://github.com/spring-cloud/spring-cloud-dataflow/pull/614/commits/6940b310245db2300262fa77c22715b94dba8f26

**Comment by trisberg** [comment]
hmm, don't think I saw that one, pulled the latest changes, but that might have been before that commit

**Comment by trisberg** [comment]
hopefully we made the same changes ;)

**Pull request closed without merging**
