### PR TITLE
Update pom to use spring boot parent

### LINKED ISSUE #978: Change local-server POM to inherit from Spring Boot parent
As a developer, I'd like to change the local-server pom.xml to inherit the foundation bits from Spring Boot parent itself. This allows us to capture project metadata, so that we can publish the final artifacts to maven central.

### PR DESCRIPTION
**Pull request by markpollack**
Fixes #978

### CODE REVIEW

**Comment by jvalkeal** [comment]
Did a diff what libs gets package to local server.
```
$ diff /tmp/ls.2 /tmp/ls.1
1d0
< accessors-smart-1.1.jar
10d8
< asm-5.0.3.jar
13d10
< assertj-core-2.5.0.jar
29,30d25
< hamcrest-core-1.3.jar
< hamcrest-library-1.3.jar
33,34c28,29
< httpclient-4.5.jar
< httpcore-4.4.1.jar
---
> httpclient-4.5.2.jar
> httpcore-4.4.5.jar
45c40
< joda-time-2.7.jar
---
> joda-time-2.9.4.jar
47,49d41
< jsonassert-1.2.3.jar
< json-path-2.2.0.jar
< json-smart-2.2.1.jar
51d42
< junit-4.12.jar
60,61d50
< mockito-core-1.10.19.jar
< objenesis-2.1.jar
87d75
< spring-boot-starter-test-1.4.1.RELEASE.jar
90,91d77
< spring-boot-test-1.4.1.RELEASE.jar
< spring-boot-test-autoconfigure-1.4.1.RELEASE.jar
109c95
< spring-cloud-task-core-1.1.0.RC1.jar
---
> spring-cloud-task-core-1.0.3.RELEASE.jar
136d121
< spring-test-4.3.3.RELEASE.jar
```
i.e. `< spring-test-4.3.3.RELEASE.jar` means that this test jar is present in master build but not with build with this PR. Weird that testing jars are there in master. Removal of `asm-5.0.3.jar` is always a red flag in case it breaks something.

**Comment by jvalkeal** [comment]
That's downgrading `spring-cloud-task-core` from `1.1.0.RC1` `to 1.0.3.RELEASE`

**Comment by trisberg** [comment]
@jvalkeal not sure why the diff between 1.0.3 and 1.1.0.RC1 is relevant to this PR

**Comment by jvalkeal** [comment]
@trisberg this PR is changing deps which gets pulled in?

**Comment by trisberg** [comment]
Not really, changes the parent pom and some dependency management, but nothing radical, the changes you see might have more to do with a Boot upgrade

**Comment by trisberg** [comment]
Hmm, I see what you are saying now, yes, that is quite a bit of differences in dependent jars pulled in

**Comment by trisberg** [comment]
It looks like the Camden BOM overrides versions from transitive deps from the `org.springframework.cloud:spring-cloud-dataflow-server-core` artifact

**Comment by trisberg** [comment]
Looks better with the task BOM included

**Comment by jvalkeal** [comment]
`spring-cloud-dataflow-server-local` pom doesn't define groupId so it gets it from `spring-boot-starter-parent` and we get `org.springframework.boot:spring-cloud-dataflow-server-local:jar:1.1.0.BUILD-SNAPSHOT`. should be `org.springframework.cloud`.

**Comment by trisberg** [comment]
Adding groupId on merge - think this is the best we can do for now

**Comment by trisberg** [comment]
Merged

**Pull request closed without merging**
