### PR TITLE
Client Evaluates EXECUTIONS_CURRENT_RELATION if version 1.7 and above

### PR DESCRIPTION
**Pull request by cppwfs**
TaskTemplate (client) extracts the numeric portion of the version number as reported by the AboutOperation
if the version is 1.7 or above then the EXECUTIONS_CURRENT_RELATION will be tested, else it will be skipped.

resolves SCDF-2401

### CODE REVIEW

**Comment by markpollack** [comment]
There is a very small library, which the cf-java-client uses, that can remove the code which is parsing out the version numbers and doing the comparison.

https://github.com/zafarkhaja/jsemver#comparing-versions

```
        <dependency>
            <groupId>com.github.zafarkhaja</groupId>
            <artifactId>java-semver</artifactId>
            <version>0.9.0</version>
        </dependency>
```

Switching to use that library means we don't have to really go crazy testing the logic added in this commit and also allows us to reuse the testing of versions in the future for other parts of the API that may require such tests (ATM it is all bundled up inside TaskTemplate. 

Otherwise looks good.

**Comment by markpollack** [comment]
Though, after trying on `1.7.0.RELEASE` it barfs, so one would have to strip the last part if it exists.  There is this issue that hasn't been addressed. https://github.com/zafarkhaja/jsemver/issues/40

**Comment by markpollack** [comment]
https://github.com/vdurmont/semver4j is more active.  I had a chat a while back with Ben Hale about his choice in library (when doing skipper) since the other library seems abandoned.  it was active at the time and apparently there was not need to change.  The semver4j works well with code like this. 

```
	@Test
	public void testSemVer() {
		Semver minRequiredVersion = new Semver("1.7.0");
		Semver currentVersion = new Semver("1.6.0");
		Assert.assertTrue(currentVersion.isLowerThan(minRequiredVersion));
		currentVersion = new Semver("1.7.1");
		Assert.assertTrue(currentVersion.isGreaterThan(minRequiredVersion));
	}
```
Either way, I think we will have to strip off the 4th place in the version to do the comparison due to 'build-snapshot' and 'release' not really being something these libraries understand.  Initializr has a library that does understand those spring conventions, but it pulls in too much.

**Comment by cppwfs** [comment]
Updated based on code review & rebased

**Comment by markpollack** [comment]
Added a VersionUtils method for reuse in other cases and added tests.

merged as 91dd1d1d04989a3920a60880b930eba74ba2049a

**Pull request closed without merging**
