### PR TITLE
Documentation on server modes

### LINKED ISSUE #1932: Document Skipper and Classic modes
As a developer, I'd like to document Skipper and Classic modes and the differences.

**Acceptance:**
- Remove the existing `stream skipper ... ` [references](https://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.M3/reference/htmlsingle/#spring-cloud-dataflow-streams-skipper) from the docs.
- Update "Streams with Skipper" section with the cosolidated commands and the prerequisites. 
- Consider adding a table walking through a use-case workflow. Perhaps a simple stream's create, deploy, and undeploy experience on one side and then the stream create, deploy, update, undeploy workflow on the other. As far as we are able to differentiate the use and the benefits, it'd be very useful.

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Add doc for using Data Flow server/shell in classic vs skipper mode
  - Update getting started doc
 - Fix stream commands to remove the `skipper` prefix

Resolves #1932

### CODE REVIEW

**Comment by tzolov** [comment]
1. Perhaps we should document the `stream info` command too? imho it provides a valuable feedback about the stream's status
2. (minor) Section: `27. Stream Lifecycle with Skipper` seems to expose some skipper implementation details that a irrelevant for scdf.  From scdf standpoint we are not interested of templates and values. It is important that our streams along with their apps are bundled as packages and their application and deployment properties can be (re)configured. The Skipper link provided allows to digg for skipper details interested
3. (minor) There is an ambiguity with the usage of the term `application`. In scdf, application usually stands for `stream app`, while in skipper it can mean any (sub)package including the scdf `stream`.

**Comment by ilayaperumalg** [comment]
@tzolov We have a story to address `stream info` documentation and I can bring it here.

**Comment by ilayaperumalg** [comment]
Updated the PR with the documentation for `stream info`. 

I have created https://github.com/spring-cloud/spring-cloud-dataflow/issues/1953 to address other comments

**Comment by viniciusccarvalho** [comment]
Merged via dd5028d5887735d38f28afa35e5f136eb2cc2a4c

**Pull request closed without merging**
