### PR TITLE
Fixed the image code

### PR DESCRIPTION
**Pull request by andrea-ligios**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@andrea-ligios Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=2304)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=2304) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@andrea-ligios Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=2304)!

**Comment by ilayaperumalg** [comment]
@andrea-ligios Thank you for your contribution!

It appears that the image renders correctly in the getting started page. 
Could you help us understand what issue do you see without your fix?

I am also attaching the image that is copied from the generated documentation:
screen shot 2018-07-10 at 11 17 43 am

To generate doc locally (and quickly):
```
./mvnw clean install -DskipTests
./mvnw clean -DskipTests -Pfull package -pl spring-cloud-dataflow-docs
```

**Comment by andrea-ligios** [comment]
@ilayaperumalg it doesn't get rendered in latest Firefox (61.0.1 64bit), I see raw code...

Version before mine: https://github.com/spring-cloud/spring-cloud-dataflow/blob/12ae4ce0c28fb5a119983bd0ce01ecf14e567b30/spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc

Output: 

immagine

I'm no expert on AsciiDoc at all (I'm MarkDown addicted), but I felt I needed to fix it. 
Please check it out with Firefox :)

**Comment by andrea-ligios** [comment]
I confirm that also in Chrome it wasn't rendering the image before my commit...

**Comment by ilayaperumalg** [comment]
@andrea-ligios Sorry about the delay responding to you. 
Now I see what you mean as the issue. It is the Github page not displaying the image while I was referring to the generated documentation published [here](http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#getting-started)

With your fix, the generated documentation misses the actual image (as it misses the AsciiDoc reference). 
I agree that this issue needs to be fixed for Github page but at the same time without breaking the generated documentation.

Please share if you have a solution that fixes both the issues. Meanwhile, I will try to see how this can be fixed and ask around for help.

Thank you for your contribution!

**Comment by ilayaperumalg** [comment]
@andrea-ligios As a follow-up, this fix resolves the issue with the documentation on the github.com page while the asciidoc images are inserted and used for the generated documentation [here](http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/). Hence, it makes sense not tring to fix this as it breaks the generated documentation.

Also, looking through the documentation pages inside `spring-cloud-dataflow-docs` from `github.com/spring-cloud/spring-cloud-dataflow` is not the suggested way to go through the documentation.

With all these reasons, I am going ahead and closing this PR though I would like to thank you again for the willingness to contribute and fix what you observed.

**Comment by ilayaperumalg** [comment]
:-) Thank you @andrea-ligios

**Pull request closed without merging**
