### PR TITLE
Remove auto registration of composed-task-runner

### LINKED ISSUE #1230: composed-task-runner registered by default
When I deploy a server implementation that build on the most recent snapshots of scdf-core I get a new `composed-task-runner` app registered:

```
composed-task-runner	task	maven://org.springframework.cloud.task.app:composedtaskrunner-task:1.0.0.BUILD-SNAPSHOT
```

Not sure why this is, but it certainly will not be useful running with the Kubernetes or Mesos servers.

### PR DESCRIPTION
**Pull request by cppwfs**
resolves #1230 

Let's check with @mminella before merging.

### CODE REVIEW

**Comment by ericbottard** [comment]
I thought we discussed this already and we concluded that this is a core feature of Data Flow itself.
Specific runtimes can override the uri of the runner to get an appropriate (eg docker) version

**Comment by ericbottard** [comment]
cc @markfisher ^^

**Comment by markfisher** [comment]
It should not be considered a "core feature" if it doesn't work for all server implementations.

**Comment by cppwfs** [comment]
But it can be configured via the dataflow-server.yml/properties/etc to
select whatever composed-task-runner is required.  The default was just
maven.

**Comment by markfisher** [comment]
I don't know if a "default" really makes sense in this case. It feels like each dataflow server should handle this explicitly.

**Comment by trisberg** [comment]
Rebased and merged as commit 2193d11ec0e3c4a7dc43eb35a9ec7886a4e54590

**Pull request closed without merging**
