### PR TITLE
Quotes

### PR DESCRIPTION
**Pull request by markpollack**
Resolves spring-cloud/spring-cloud-dataflow#2587

### CODE REVIEW

**Comment by markpollack** [comment]
```
dataflow:>stream create test3 --definition "time | filter --expression='#jsonPath(payload,'$.lang')=='en'' | log"
Created new stream 'test3'
dataflow:>stream list
╔══════════╤═══════════════════════════════════════════════════════════════════╤═══════════════════════════════════════════════════════════════════╗
║  Stream  │                         Stream Definition                         │                              Status                               ║
║   Name   │                                                                   │                                                                   ║
╠══════════╪═══════════════════════════════════════════════════════════════════╪═══════════════════════════════════════════════════════════════════╣
║test3     │time | filter --expression='#jsonPath(payload,'$.lang')=='en'' |   │The app or group is known to the system, but is not currently      ║
║          │log                                                                │deployed                                                           ║
╚══════════╧═══════════════════════════════════════════════════════════════════╧═══════════════════════════════════════════════════════════════════╝

dataflow:>stream de
stream deploy     stream destroy    
dataflow:>stream deploy --name test3
Deployment request has been sent for stream 'test3'
dataflow:>stream list
╔═══════════╤═══════════════════════════════════════════════════════════════════════════╤═════════════════════════════╗
║Stream Name│                             Stream Definition                             │           Status            ║
╠═══════════╪═══════════════════════════════════════════════════════════════════════════╪═════════════════════════════╣
║test3      │time | filter --filter.expression='#jsonPath(payload,'$.lang')=='en'' | log│The stream is being deployed.║
╚═══════════╧═══════════════════════════════════════════════════════════════════════════╧═════════════════════════════╝
```

**Comment by markpollack** [comment]
I tried to use the `quoteUsed` property to know when to strip off quotes if the argument name contained the word `expresion`, however, it seems for a value of `'#jsonPath(payload,'$.lang')=='en''` the ArgumentNode gives a quoteUsed=null value....

**Comment by markpollack** [comment]
Maybe we can use a more bizarre character other than `,` for the case of the alternate stream application DSL syntax to avoid this conflict?  That would be a breaking change for users who are adopting this new DSL, but that is far fewer than those using the existing DSL.

```
--definition "aaa ; bbb"
--definition "aaa <-> bbb"
```

**Comment by markpollack** [comment]
Another option is to have an additional command option that would be used to indicate which type of DSL is being parsed.

**Comment by sabbyanandan** [comment]
Closing this in favor of #2618.

**Pull request closed without merging**
