### PR TITLE
Set INDEX_PROPERTY_KEY only when upstream app is partitioned

### LINKED ISSUE #1876: Only set indexed property when deploying a partitioned stream
By setting this even for regular stream deployments, as a side effect, we are spawning StatefulSet pods in K8S, which is unnecessary. The requirement is to make sure it is applied only when a partitioned streaming characteristics are implied.

### PR DESCRIPTION
**Pull request by markpollack**
Also backport to 1.3.x branch

Fixes #1876

### CODE REVIEW

**Comment by tzolov** [comment]
@markpollack the `SkipperStreamServiceIntegrationTests#testInstallVersionOverride` is failing. 
Perhaps we should drop the `spring.cloud.deployer.indexed: 'true'` line from the `SkipperStreamServiceIntegrationTests-install.yml` test feature?

**Comment by tzolov** [comment]
Rebased and merged at d75f841e

**Comment by tzolov** [comment]
Rebased and merged at d75f841

**Comment by markpollack** [comment]
also needed to apply to 1.3.x branch

**Pull request closed without merging**
