### PR TITLE
gh-899 Fix Rest-Doc Generation

### PR DESCRIPTION
**Pull request by ghillert**
Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/899

### CODE REVIEW

**Comment by jvalkeal** [comment]
It broke shell
```
$ java -jar spring-cloud-dataflow-shell/target/spring-cloud-dataflow-shell-1.1.0.BUILD-SNAPSHOT.jar 
no main manifest attribute, in spring-cloud-dataflow-shell/target/spring-cloud-dataflow-shell-1.1.0.BUILD-SNAPSHOT.jar
```
New executable fatjar became `spring-cloud-dataflow-shell-1.1.0.BUILD-SNAPSHOT-exec.jar` and original `spring-cloud-dataflow-shell-1.1.0.BUILD-SNAPSHOT.jar` doesn't execute anymore.

With #793 I'm splitting shell into `spring-cloud-dataflow-shell` and `spring-cloud-dataflow-shell-core` which would fix this issue but I didn't issue PR yet.

**Comment by jvalkeal** [comment]
I'd recommend that you (1) revert those shell changes, (2) disable related test and let docs missing what's related to that. Then I (3) PR #793 and we can start to use `spring-cloud-dataflow-shell-core` which is not a fatjar.

**Comment by ghillert** [comment]
Reworked the PR based on the changes implemented with https://github.com/spring-cloud/spring-cloud-dataflow/issues/793

This eliminates any braking changes.

**Comment by jvalkeal** [comment]
ok, think this looks good, merging

**Pull request merged**
