### PR TITLE
Task definition limit

### LINKED ISSUE #4190: Need to verify that task def name < 64 char when launching on CF or K8s
When user launches a task definition and the user selects a platform that is CF or K8s be sure to verify that the task definition name is less that 64 characters.   If not return a meaningful error message vs. the one returned from the platform.

### PR DESCRIPTION
**Pull request by siddhantsorann**
This PR fixes #4190 

- Added validation when the task is launched depending on the platform launched in. 
- Returns a meaningful message if the task was > 63 characters.

### CODE REVIEW

**Comment by jvalkeal** [comment]
@siddhantsorann It'd be good if you could rebase a PR branch without adding merge commits as only way to merge PR like is is to merge/squash and then physically change back original author.

**Comment by siddhantsorann** [comment]
> @siddhantsorann It'd be good if you could rebase a PR branch without adding merge commits as only way to merge PR like is is to merge/squash and then physically change back original author.

Hey @jvalkeal noted. I'll raise another PR with the squashed commits then?

**Comment by jvalkeal** [comment]
You could just force push into your branch PR branch.

**Comment by siddhantsorann** [comment]
> You could just force push into your PR branch.

@jvalkeal Faced some issue so I created another PR - https://github.com/spring-cloud/spring-cloud-dataflow/pull/4203

**Comment by siddhantsorann** [comment]
@jvalkeal Faced an issue, have raised another PR with one commit - https://github.com/spring-cloud/spring-cloud-dataflow/pull/4203

**Pull request closed without merging**
