### PR TITLE
Remove references to enableLocalPlatform

### LINKED ISSUE #2972: Remove ref to enableLocalPlatform

### PR DESCRIPTION
**Pull request by markpollack**
Fixes #2972

### CODE REVIEW

**Comment by chrisjs** [comment]
when testing these changes on kubernetes against the latest published skipper image, i see the following in the logs:

```
2019-03-03 16:50:41.897  INFO 1 --- [           main] .c.s.s.s.RepositoryInitializationService : Initializing repository database for name local
2019-03-03 16:50:42.166  INFO 1 --- [           main] .s.c.s.s.s.DeployerInitializationService : Added 'Local' platform account 'default' into deployer repository.
2019-03-03 16:50:42.166  INFO 1 --- [           main] .s.c.s.s.s.DeployerInitializationService : Added 'Kubernetes' platform account 'default' into deployer repository.
2019-03-03 17:01:17.628  INFO 1 --- [nio-7577-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
```

and then when trying to deploy a stream i get the following snippet of exception:

```
Caused by: java.io.IOException: Cannot run program "docker" (in directory "/tmp/spring-cloud-deployer-4154480461099449832/ticktock-1551632491687/ticktock.time-v1"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_192]
	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer$AppInstance.start(LocalAppDeployer.java:397) ~[spring-cloud-deployer-local-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer$AppInstance.start(LocalAppDeployer.java:421) ~[spring-cloud-deployer-local-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer$AppInstance.access$200(LocalAppDeployer.java:307) ~[spring-cloud-deployer-local-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.cloud.deployer.spi.local.LocalAppDeployer.deploy(LocalAppDeployer.java:210) ~[spring-cloud-deployer-local-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	... 51 common frames omitted
Caused by: java.io.IOException: error=2, No such file or directory
```

looks like local deployer is being used

**Comment by chrisjs** [comment]
poking around, I'm thinking https://github.com/spring-cloud/spring-cloud-skipper/pull/834 is a dependency for this PR, ya?

**Comment by ilayaperumalg** [comment]
@chrisjs Yes, that's the case here. Once k8s account is in there, the `local` deployer account is not expected to be in the deployer repository. 

We are good now that spring-cloud/spring-cloud-skipper#834 is merged

**Comment by chrisjs** [comment]
looks good now, merging

**Comment by chrisjs** [comment]
merged in facd2fde

**Pull request closed without merging**
