### PR TITLE
[Do Not Merge] Deploying Spring Boot 3 on Cloud Foundry 

### PR DESCRIPTION
**Pull request by corneil**
Provide for setting cloudfoundry deployer options for deploying Spring Boot 3 applications requiring JDK 17.

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
These changes LGTM. But, let's wait until we complete the 2.11.1 release as the users have a way to set these properties via other ways - app/deployer properties.

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
The JBP_CONFIG_OPEN_JDK_JRE was passed in as a application property, not a deployer property.   i.e.  `timestamp3 --JBP_CONFIG_OPEN_JDK_JRE='{jre: {version: 17.+}}'`

**Comment by corneil** [comment]
> The JBP_CONFIG_OPEN_JDK_JRE was passed in as a application property, not a deployer property. i.e. `timestamp3 --JBP_CONFIG_OPEN_JDK_JRE='{jre: {version: 17.+}}'`

Update the code.

**Comment by cppwfs** [comment]
LGTM!

**Comment by cppwfs** [comment]
We just need to add the quotes to the JDK version.  I think that is it.

**Pull request merged**
