### PR TITLE
Fix deletion of batch job instances when cleaning up task executions

### PR DESCRIPTION
**Pull request by hpoettker**
This is a fix for gh-4233

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hpoettker Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4234)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4234) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hpoettker Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow&pullRequestId=4234)!

**Comment by ilayaperumalg** [comment]
@hpoettker Thanks for the PR!

The changes look good to me and hence merging.

**Comment by ilayaperumalg** [comment]
Cherry-picked and back ported the changes into 2.6.x as 9f9c06aeb

**Pull request merged**
