### PR TITLE
Create metrics endpoint for streams

### LINKED ISSUE #1286: Create metrics endpoint to support the Flo UI
The SCDF /metrics endpoint should return mostly what the metrics collector is returning

### PR DESCRIPTION
**Pull request by jvalkeal**
- Add a simple MetricsController meant to be a proxy
  for collector metrics and used by flo.
- Attatch to security ad VIEW rights
- For now keeping this out from RootController as
  we'd need Resource type and that is not known until
  collector adds hal stuff.
- Fixes #1286

### CODE REVIEW

**Comment by BoykoAlex** [comment]
@jvalkeal looks like the endpoint lists all metrics for all streams, right? I cannot pass the list of streams I'm interested in?

**Comment by jvalkeal** [comment]
@BoykoAlex  We'll add that when collector app supports it.

**Comment by BoykoAlex** [comment]
@jvalkeal one more thing. I'm trying to work off this PR. I have deployed a stream and trying to see what HTTP GET on `http://localhost:9393/metrics/streams` gives me. It just gives a `200` response... Looks like I'm missing something... Do in need to to enable something in the `dataflow-server.yml` to see metrics... Latest version of local deployer locally perhaps? Any advice?

**Comment by BoykoAlex** [comment]
It works fine for me. Stuff requiring some polish is in the collector anyway. I'll merge this PR - it's LGTM

**Comment by BoykoAlex** [comment]
Merged with aaa74e01c974dda4b12b70edaaf3104493696070

**Pull request closed without merging**
