### PR TITLE
[Do not merge yet] Add a Kubernetes Deployer implementation

### PR DESCRIPTION
**Pull request by ericbottard**
This builds on top of https://github.com/spring-cloud/spring-cloud-dataflow/pull/113 where a lot of discussion has already happened.

My commit decouples the previous implementation from hardcoded redis requirement by introducing Spring Cloud Connector for Kubernetes.

Here are the things I think that should still be addressed, not necessarily as part of this PR:
* this deployer, as the Marathon one, does not support `module.index`. Maybe fail deployment in case partitioning is requested
* The `kubernetesClient` object is currently created with the simple constructor, using configuration that is drawn from ENV_VARS and system props (like documented [here](https://github.com/fabric8io/kubernetes-client)). We should rather use the constructor that takes an explicit `Config` and use boot `@ConfigurationProperties`, for consistency
* The original PR by @frosenberg added an IT test, but this requires a running kubernetes cluster. Execution of that test should be made optional thanks to a JUnit rule (test is currently disabled)

Apart from that, I think this is now in a state that can sustain further review, and is a good candidate for merge

### CODE REVIEW

**Comment by donovanmuller** [comment]
Looking forward to this :+1:

**Comment by markpollack** [comment]
I've spend about 4-5 hrs now trying to get kubernetes going on EC2 (many permission errors) and also using vagrant (broken vmware provider - see https://github.com/kubernetes/kubernetes/issues/10906).  

Trying the docker approach in the original PR is  more promising however I think something maybe wrong with versions.  @frosenberg any ideas what maybe causing this issue?   Note I am running on a windows host with a ubuntu 14.04 guest os via vmware workstation 12.

```
$ kubectl create -f src/main/kubernetes/redis-controller.yml 
Error: unable to recognize "src/main/kubernetes/redis-controller.yml": no object named "ReplicationController" is registered
```
```
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"15", GitVersion:"v0.15.0", GitCommit:"831f3e60d7cd64c61a775d6c78acce1673dd8aa9", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.6", GitCommit:"388061f00f0d9e4d641f9ed4971c775e1654579d", GitTreeState:"clean"}
```

```
$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080
```
not sure why the UI isn't running

```
$ docker --version
Docker version 1.7.1, build 786b29d
```

```
$ docker-compose --version
docker-compose version: 1.4.2
```

```
$ docker-machine --version
docker-machine version 0.5.0 (04cfa58)
```

I may try the vagrant+virtualbox option (though I've had issues in the past running virtualbox inside workstation) or figure out the EC2 route.

**Comment by frosenberg** [comment]
Sorry @markpollack. For some reason i'm not receiving notifications for this project anymore.  Try starting k8s with these scripts: https://github.com/vyshane/docker-compose-kubernetes

They work pretty well for me. If you run virtualbox, the Linux version should be good to go.

**Comment by markpollack** [comment]
This have moved to https://github.com/spring-cloud/spring-cloud-dataflow-admin-kubernetes

**Pull request closed without merging**
