### PR TITLE
Improve getting started doc

### LINKED ISSUE #413: User guide quick start http POST fails
```
$ java -jar spring-cloud-dataflow-shell-1.0.0.M2.jar
...
Welcome to the Spring Cloud Data Flow shell. For assistance hit TAB or type "help".
dataflow:>stream create --name httptest --definition "http --server.port=9000 | log" --deploy
Created and deployed new stream 'httptest'
dataflow:>http post --target http://localhost:9000 --data "hello world"
> POST (text/plain;Charset=UTF-8) http://localhost:9000 hello world
Failed to access http endpoint http://localhost:9000
```

There's no error in the admin server console.

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Update version `BUILD-SNAPSHOT` instead of `M2`
 - Add more detail in the steps

This resolves #413

### CODE REVIEW

**Comment by markpollack** [comment]
Just changing to snapshot won't work as snapshot adds the date to the jar name. I have a snippit of a mvn command that downloads the latest snapshot.  I'll post it here when I get a moment later tonight.

**Comment by ilayaperumalg** [comment]
I tested the steps (including the `wget`) fine. It downloads the latest snapshot.

**Comment by markpollack** [comment]
yep, my bad - artifactory is smart.

**Comment by markpollack** [comment]
master already had some changed.  Merged and committed as 494efc4ddae8a271b86c00c03113a444884fe91a with some minor asciidoc polish

**Pull request closed without merging**
