### PR TITLE
Add deployment properties to LauncherRepository

### LINKED ISSUE #3121: Add deployer properties to LauncherRepository
A continuation of what we did via https://github.com/spring-cloud/spring-cloud-dataflow/issues/3057. To do this, we will have to revisit the overall Task/Batch lifecycle management semantics in SCDF. CI/CD for Tasks is one of the goals when we revisit the topic.

### PR DESCRIPTION
**Pull request by jvalkeal**
- This commit is basically same done for stream deployers where
  `/streams/deployments/platform/list` exposes deployers with possible
  deployment options. For this same dance is done for `/tasks/platforms`.
- Add options field to LauncherResource entity denoting possible
  deployment properties known to each deployer type.
- Read all known deployer related properties and update
  those to LauncherRepository during initialization phase.
- There's no actual user for these new fields for now but having
  those in place allows to start work to make task launch page UI
  to be more consistent with stream deploy UI.
- Has same black/white listing options under
 `spring.cloud.dataflow.task.deployer-properties` which are currently just
  copied from stream side. These would then get polished or redefined when
  actual UI side implementation starts.
- Fixes #3121

For example:
```
curl http://localhost:9393/tasks/platforms|jq
{
  "_embedded": {
    "launcherResourceList": [
      {
        "name": "default",
        "type": "Local",
        "description": "ShutdownTimeout = [30], EnvVarsToInherit = [TMP,LANG,LANGUAGE,LC_.*,PATH,SPRING_APPLICATION_JSON], JavaCmd = [/usr/lib/jvm/java-8-oracle/jre/bin/java], WorkingDirectoriesRoot = [/tmp], DeleteFilesOnExit = [true]",
        "options": [
          {
            "id": "spring.cloud.deployer.local.debug-suspend",
            "name": "debug-suspend",
            "type": "java.lang.String",
            "description": null,
            "shortDescription": null,
            "defaultValue": null,
            "hints": {
              "keyHints": [],
              "keyProviders": [],
              "valueHints": [
                {
                  "value": "y",
                  "description": null,
                  "shortDescription": null
                },
                {
                  "value": "n",
                  "description": null,
                  "shortDescription": null
                }
              ],
              "valueProviders": []
            },
            "deprecation": null,
            "deprecated": false
          },
```

### CODE REVIEW

**Comment by cppwfs** [comment]
LGTM
Is this something we need to merge for the M2 milestone?

**Comment by sabbyanandan** [comment]
It'd be good to pull it in for 2.3 M2.

**Comment by cppwfs** [comment]
But... But... But... I wanted to go to Tosche station to pick up power
converters :-D

**Comment by cppwfs** [comment]
Squashed, Rebased, merged

**Pull request closed without merging**
